### ISSUE TITLE
Script does nothing [BUG]

### ISSUE THREAD

**Issue by nopenononope** [charlesbel/Microsoft-Rewards-Farmer#100]
I open the script and it opens a command prompt window and quickly closes. I have installed all requirements and added my account info.

**Comment by TommasoAscani** [comment]
Did you download the chrome driver?

**Comment by nopenononope** [comment]
> Did you download the chrome driver?

Yes I forgot to mention that.

**Comment by Zaavra** [comment]
did you put chromedriver.exe in C:/Windows

**Comment by kokokoko5656** [comment]
i have the same problem but im on windows

**Comment by Lofifr** [comment]
Hello,
I have simular issue. 
I installed chromedriver.exe in C:/Windows
Do the pip install -r requirements.txt
Set account in accounts.json

When running ms_rewards_farmer.py I got thoses messages : 
Traceback <most recent call last>:
File "C:\Users\XXX\ms_rewards_farmer\ms_rewards_farmer.py", line 766, in <module>
random.shuffle<ACCOUNTS>
File "C:\Users\XXX\Python\Python310\lib\random.py", line 394, in shuffle
x[i], x[j] = x[j], x[i]
KeyError: 0

Could you help me please?

**Comment by FRKFFR** [comment]
someone re created the bot https://github.com/MehdiRtal/MicrosoftRewardsBot.git

**Comment by AbyssalKaz** [comment]
Having the same issue myself, any assistance would be nice :D

**Comment by charlesbel** [comment]
Fixed with v3.0 #188
