### ISSUE TITLE
[BUG] Stuck on "Ensuring login on Bing..."

### ISSUE THREAD

**Issue by Zaavra** [charlesbel/Microsoft-Rewards-Farmer#102]
![image](https://user-images.githubusercontent.com/96395992/183223467-e09901f0-acd6-4a73-8399-bc2cb2920f73.png)
It stops when it hits this message.

**Comment by Zaavra** [comment]
Fixed! Remove Line 86:
checkBingLogin(browser, isMobile)

**Comment by Xyl3ntHacks** [comment]
Thanks!
