### ISSUE TITLE
[BUG] 'find_element_by_name'

### ISSUE THREAD

**Issue by JJ34D** [charlesbel/Microsoft-Rewards-Farmer#104]
Traceback (most recent call last):
  File "C:\Users\User\Downloads\Microsoft-Rewards-Farmer-master\Microsoft-Rewards-Farmer-master\ms_rewards_farmer.py", line 773, in <module>
    login(browser, account['username'], account['password'])
  File "C:\Users\User\Downloads\Microsoft-Rewards-Farmer-master\Microsoft-Rewards-Farmer-master\ms_rewards_farmer.py", line 46, in login
    browser.find_element_by_name("loginfmt").send_keys(email)
AttributeError: 'WebDriver' object has no attribute 'find_element_by_name'

**Comment by Hikaru4v** [comment]
You're using the wrong version of the web driver.

Try selenium 3.1.4 and also ensure you're using the appropriate chrome version for whatever you have downloaded on your PC

**Comment by silasish** [comment]
You must have downloaded the GitHub release, you need to clone the latest instead. (for some reason the "release" uses `find_element_by_name` which no longer exists)

**Comment by inverspe** [comment]
> You must have downloaded the GitHub release, you need to clone the latest instead. (for some reason the "release" uses `find_element_by_name` which no longer exists)

can you please tell how do i clone the latest release

**Comment by Dangman368** [comment]
i have a fix for this. it worked for me. all you have to do is go to requirements.txt and replace the selenium text with selenium==3.14.1

**Comment by FRKFFR** [comment]
someone re created the bot https://github.com/MehdiRtal/MicrosoftRewardsBot.git

**Comment by charlesbel** [comment]
Fixed with v3.0 #188
