### ISSUE TITLE
bug : error when connecting to another account

### ISSUE THREAD

**Issue by Lofifr** [charlesbel/Microsoft-Rewards-Farmer#106]
Hello,
When I'm connecting to another account I got the following error message :
I checked by login manual I don't have any verification to login

Traceback (most recent call last):
  File "C:\Users\Desktop\Microsoft-Rewards-Farmer-master v2\Microsoft-Rewards-Farmer-master\ms_rewards_farmer.py", line 773, in <module>
    login(browser, account['username'], account['password'])
  File "C:\Users\Desktop\Microsoft-Rewards-Farmer-master v2\Microsoft-Rewards-Farmer-master\ms_rewards_farmer.py", line 43, in login
    waitUntilVisible(browser, By.ID, 'loginHeader', 10)
  File "C:\Users\Desktop\Microsoft-Rewards-Farmer-master v2\Microsoft-Rewards-Farmer-master\ms_rewards_farmer.py", line 160, in waitUntilVisible
    WebDriverWait(browser, time_to_wait).until(ec.visibility_of_element_located((by_, selector)))
  File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
Backtrace:
	Ordinal0 [0x00F578B3+2193587]
	Ordinal0 [0x00EF0681+1771137]
	Ordinal0 [0x00E041A8+803240]
	Ordinal0 [0x00E324A0+992416]
	Ordinal0 [0x00E3273B+993083]
	Ordinal0 [0x00E5F7C2+1177538]
	Ordinal0 [0x00E4D7F4+1103860]
	Ordinal0 [0x00E5DAE2+1170146]
	Ordinal0 [0x00E4D5C6+1103302]
	Ordinal0 [0x00E277E0+948192]
	Ordinal0 [0x00E286E6+952038]
	GetHandleVerifier [0x01200CB2+2738370]
	GetHandleVerifier [0x011F21B8+2678216]
	GetHandleVerifier [0x00FE17AA+512954]
	GetHandleVerifier [0x00FE0856+509030]
	Ordinal0 [0x00EF743B+1799227]
	Ordinal0 [0x00EFBB68+1817448]
	Ordinal0 [0x00EFBC55+1817685]
	Ordinal0 [0x00F05230+1856048]
	BaseThreadInitThunk [0x75DAFA29+25]
	RtlGetAppContainerNamedObjectPath [0x77677A9E+286]
	RtlGetAppContainerNamedObjectPath [0x77677A6E+238]

Can you help me please?
Thank you

**Comment by Andrew1644563** [comment]
Hello, just wanted to know why you are switch accounts/what do you mean because the program has a multiple-account option you can add in the account.json file.

**Comment by Lofifr** [comment]
Hello Andrew,
In fact it's more related when the bot finished an account and want to connect to another account.
I'm editing the first post.

**Comment by FRKFFR** [comment]
someone re created the bot https://github.com/MehdiRtal/MicrosoftRewardsBot.git

**Comment by charlesbel** [comment]
Fixed with v3.0 #188
