### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by wacklack** [charlesbel/Microsoft-Rewards-Farmer#108]
searches on bing can take hours to complete sometimes taking an hour for one to happen.

**Comment by Eugene-Tong** [comment]
did you turn off the headless and see which page it is stuck in?

**Comment by wacklack** [comment]
>

**Comment by wacklack** [comment]
how do i run in headless mode @Eugene-Tong

**Comment by Eugene-Tong** [comment]
you can turn the headless = False when calling the function, I think there are 2 functions to change line 771 and 811

**Comment by wacklack** [comment]
i ran it in headless mode it didnt get stuck on any page it kept serching but my points didnt go up and neither did the progress in the command prompt @Eugene-Tong

**Comment by Andrew1644563** [comment]
> searches on bing can take hours to complete sometimes taking an hour for one to happen.

Agreed, is there any way we can make this faster?

**Comment by FRKFFR** [comment]
someone re created the bot https://github.com/MehdiRtal/MicrosoftRewardsBot.git

**Comment by charlesbel** [comment]
Fixed with v3.0 #188
