### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by harunresitc** [charlesbel/Microsoft-Rewards-Farmer#109]
TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

**Comment by Andrew1644563** [comment]
Did you leave it on for too long? Could also be Selenium just timing out. Do you still have this issue?

**Comment by LuckiestOne23** [comment]
As @Andrew1644563 noted, should not be caused by the program itself, more likely due to poor internet connection or anything with selenium. Restart it.

**Comment by FRKFFR** [comment]
someone re created the bot https://github.com/MehdiRtal/MicrosoftRewardsBot.git

**Comment by charlesbel** [comment]
Fixed with v3.0 #188
