### ISSUE TITLE
Question: Can I run the script multiple times for different accounts at the same time for max efficiency?

### ISSUE THREAD

**Issue by Andrew1644563** [charlesbel/Microsoft-Rewards-Farmer#110]
Question in the title, just a question that I was curious about.

**Comment by LuckiestOne23** [comment]
Yes. Multi-threading isn't a thing and you might get issues regarding too many requests (d-dos protection).

**Comment by FRKFFR** [comment]
someone re created the bot https://github.com/MehdiRtal/MicrosoftRewardsBot.git
