### ISSUE TITLE
How to turn on/off headless mode?

### ISSUE THREAD

**Issue by inverspe** [charlesbel/Microsoft-Rewards-Farmer#114]
how do i turn it on or off?

**Comment by inverspe** [comment]
also what is it for?

**Comment by LuckiestOne23** [comment]
Turn it on and off by changing the browserSetup()-Argument to True/False. For more information on headless, refer to [chrome-docs](https://developer.chrome.com/blog/headless-chrome/

**Comment by FRKFFR** [comment]
someone re created the bot https://github.com/MehdiRtal/MicrosoftRewardsBot.git

**Comment by AlexyGalaxy** [comment]
-How to Disable Headless mode to watch the script work. Comment out around line 30 and 31

#if headless_mode : #comment out to disable headless mode (makes window visable)
#options.add_argument("--headless")

**Comment by skyfl3x** [comment]
best to not activate headless mode just add this line before the return browser part 
![image](https://user-images.githubusercontent.com/117779189/236681822-aab4c2ae-67d3-4ad7-b9b0-023e2abee5b5.png)
