### ISSUE TITLE
Instant Crashing Upon Opening Python File

### ISSUE THREAD

**Issue by FenixRising76** [charlesbel/Microsoft-Rewards-Farmer#116]
*MAKE SURE THE ERROR IS NOT FROM YOU, THIS IS THE MOST FREQUENT CASE*

**Error Log**
N/A

**Screenshot of the page**
Has some text appear, then immediately closes

**Source code of dashboard**
(https://gist.github.com/FenixRising76/2d97febc9eba492ab987ff1751c710b2)

**Comment by charlesbel** [comment]
Fixed with v3.0 #188
