### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by beenruuu** [charlesbel/Microsoft-Rewards-Farmer#117]
Hello, I have tried the bot in a new account and it is not able to get all the points the account is totally new, later I have tried with another account that I have used more times and in neither of the two the quizzes are completed, I do not know if is it my mistake or what but the terminal does not give me any error.

 I only changed the path and removed an option (line 87) because the page was looping.

**Comment by FRKFFR** [comment]
someone re created the bot https://github.com/MehdiRtal/MicrosoftRewardsBot.git

**Comment by Andrew1644563** [comment]
Try to not change the path and only remove line 87 if a looping error is happening. What is the reason that cause you to change the path?

**Comment by AlexyGalaxy** [comment]
> Hello, I have tried the bot in a new account and it is not able to get all the points the account is totally new, later I have tried with another account that I have used more times and in neither of the two the quizzes are completed, I do not know if is it my mistake or what but the terminal does not give me any error.
> 
> I only changed the path and removed an option (line 87) because the page was looping.

Make sure you have manually logged into your bing rewards account and clicked join microsoft rewards to show you the "Microsoft Bing Dashboard". Brand new accounts have trouble running the script.

You also need to check your accounts file to make sure it has correct syntax and check your main .py file to make sure it has correct syntax. If you have something out of place the script will do this. Id reccomend using Visual Studios Code. Once open it should recommend you to install a python extention. Then Visual Studios Code should recomend changes to help make the script run.

Or uninstall and redownload. Here is a README I have created for this project to help. Good Luck.

README How to Install:
-Install zip from GitHub: https://github.com/charlesbel/Microsoft-Rewards-Farmer

-Install Python https://www.python.org/downloads/
Select custom installation, change nothing hit yes until installed.

-Open Microsoft-Rewards-Farmer-master, move requirements.txt to C:\Users\Alex

-Open command prompt. win + R>CMD, then type (without quotes): 'pip install -r requirements.txt' Press enter

-Intall Google Chrome.

-Install ChromeDriver from https://chromedriver.chromium.org/downloads
Place the file in X:\Windows (X as your Windows disk letter)

-Edit the accounts.json.sample with your accounts credentials and rename it by removing .sample at the end
If you want to add more than one account, the syntax is the following :
[
{
"username": "Your Email",
"password": "Your Password"
},
{
"username": "Your Email",
"password": "Your Password"
}
]

-How to Fix Mobile:
Comment out around line 134-137 with three double quotes above and below
"""
#Refresh page
browser.get('https://bing.com/')
#Wait 5 seconds
time.sleep(10)
"""

-How to run Script:
Run the script by double clicking on ms_rewards_farmer.py
