### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Abel6669** [charlesbel/Microsoft-Rewards-Farmer#125]
Mobile searches not working, woint log in

**Comment by DerMuffin** [comment]
see

https://github.com/MehdiRtal/MicrosoftRewardsBot/issues/27

**Comment by AlexyGalaxy** [comment]
> Mobile searches not working, woint log in

-How to Fix Mobile:
Comment out around line 134-138 with double quotes above and below
""
#Refresh page
browser.get('https://bing.com/')
#Wait 5 seconds
time.sleep(10)
#Update Counter
""

**Comment by charlesbel** [comment]
Fixed with v3.0 #188
