### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ryanali54** [charlesbel/Microsoft-Rewards-Farmer#126]
Traceback (most recent call last):
  File "c:\Users\ryan\Downloads\Compressed\Microsoft-Rewards-Farmer-master\ms_rewards_farmer.py", line 779, in <module>
    waitUntilVisible(browser, By.XPATH, '//*[@id="navs"]/div/div/div/div/div[4]/a', 20)
  File "c:\Users\ryan\Downloads\Compressed\Microsoft-Rewards-Farmer-master\ms_rewards_farmer.py", line 160, in waitUntilVisible
    WebDriverWait(browser, time_to_wait).until(ec.visibility_of_element_located((by_, selector)))
  File "C:\Users\ryan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\support\wait.py", line 90, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

this error occured and i ran the file in vc code
it ran for sometime then after the error it stopped
and i didnt made any changes to the main file i did all as instructed and second account was also added so it didnt get logged in

**Comment by AlexyGalaxy** [comment]
> Traceback (most recent call last): File "c:\Users\ryan\Downloads\Compressed\Microsoft-Rewards-Farmer-master\ms_rewards_farmer.py", line 779, in waitUntilVisible(browser, By.XPATH, '//*[@id="navs"]/div/div/div/div/div[4]/a', 20) File "c:\Users\ryan\Downloads\Compressed\Microsoft-Rewards-Farmer-master\ms_rewards_farmer.py", line 160, in waitUntilVisible WebDriverWait(browser, time_to_wait).until(ec.visibility_of_element_located((by_, selector))) File "C:\Users\ryan\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\selenium\webdriver\support\wait.py", line 90, in until raise TimeoutException(message, screen, stacktrace) selenium.common.exceptions.TimeoutException: Message:
> 
> this error occured and i ran the file in vc code it ran for sometime then after the error it stopped and i didnt made any changes to the main file i did all as instructed and second account was also added so it didnt get logged in

Make sure you have manually logged into your bing rewards account and clicked join microsoft rewards to show you the "Microsoft Bing Dashboard".

If that doesnt work, comment out the following lines of code around line 31 and 32 to disable headless mode and watch the script work.

if headless_mode : #comment out to disable headless mode (makes window visable)
options.add_argument("--headless")

**Comment by charlesbel** [comment]
Fixed with v3.0 #188
