### ISSUE TITLE
This should probably be updated

### ISSUE THREAD

**Issue by ghost** [charlesbel/Microsoft-Rewards-Farmer#128]
Microsoft always makes patches with scripts like these. If you wanna redeem something with the farmed points the order request gets blocked and your Microsoft rewards account gets suspended, I tried it like 6 times on alt accounts, even if you use an VPN it can still somehow detect your location, I'd advise to use the newest scripts as soon as they come out so they won't get patched because every single rewards farmer isn't working and it's a waste of time.

I hope somebody can make a fixed one soon.

**Comment by tommaso-ascani** [comment]
I didn't understand what you are saying.
If i use a script like this when i try to redeem something they suspend my account?

**Comment by DimaRazb** [comment]
@tommaso-ascani Try to redeem any reward and you will see. Back a couple of years ago I could use the same account for months and they were not suspended.

**Comment by DimaRazb** [comment]
Yep, that's pretty much it. Cause you are not supposed to automate points harvesting- so MS have all the right to suspend these accounts.

**Comment by DimaRazb** [comment]
When you automate the points farm of course, I think cause MS is banning them from looking at Selenium driver values. You can easily check that redeeming Amazon card.

**Comment by tommaso-ascani** [comment]
I don't think they can clearly see if you are using selenium, i think instead that they control the timing and the recourive of actions

**Comment by AlexyGalaxy** [comment]
> I don't think they can clearly see if you are using selenium, i think instead that they control the timing and the recourive of actions

If you are worried change parts of the code by making the "radom timer" time larger. I put this at the end of my code so that if I run more than one account the scrip will wait 200-300 secs before starting another account.

time.sleep(random.randint(200, 300))

**Comment by charlesbel** [comment]
Fixed with v3.0 #188
