### ISSUE TITLE
[BUG] Problem

### ISSUE THREAD

**Issue by BrumicekCZE** [charlesbel/Microsoft-Rewards-Farmer#129]
Hi, I have this problem:

![image](https://user-images.githubusercontent.com/91915443/199840784-8633e8e7-917e-4b56-926e-337d587e4f2a.png)

**Comment by AlexyGalaxy** [comment]
> Hi, I have this problem:
> 
> ![image](https://user-images.githubusercontent.com/91915443/199840784-8633e8e7-917e-4b56-926e-337d587e4f2a.png)

Make sure you have manually logged into your bing rewards account and clicked join microsoft rewards to show you the "Microsoft Bing Dashboard".

If that doesnt work, comment out the following lines of code around line 31 and 32 to disable headless mode and watch the script work.

if headless_mode : #comment out to disable headless mode (makes window visable)
options.add_argument("--headless")

**Comment by charlesbel** [comment]
Fixed with v3.0 #188
