### ISSUE TITLE
update

### ISSUE THREAD

**Issue by corn674** [charlesbel/Microsoft-Rewards-Farmer#130]
needs update! client socket handshake failed ssl errors not finishing mobile or should say start mobile search

**Comment by inverspe** [comment]
I get the same result

**Comment by AlexyGalaxy** [comment]
Uninstall and install using this 

**README How to Install:**
Install zip from GitHub: https://github.com/charlesbel/Microsoft-Rewards-Farmer

Install Python https://www.python.org/downloads/
	Select custom installation, change nothing hit yes until installed. 

Open Microsoft-Rewards-Farmer-master, move requirements.txt to C:\Users\Alex

Open command prompt. win + R>CMD, then type (without quotes): 'pip install -r requirements.txt' 	Press enter

Intall Google Chrome.

Install ChromeDriver from https://chromedriver.chromium.org/downloads
	Place the file in X:\Windows (X as your Windows disk letter)

Edit the accounts.json.sample with your accounts credentials and rename it by removing .sample at the end
If you want to add more than one account, the syntax is the following :
[
    {
        "username": "Your Email",
        "password": "Your Password"
    },
    {
        "username": "Your Email",
        "password": "Your Password"
    }
]


How to Fix Mobile:
Comment out around line 134-138 with double quotes above and below 
    ""
    # Refresh page
    browser.get('https://bing.com/')
    # Wait 5 seconds
    time.sleep(10)
    #Update Counter
    ""

How to run Script:
Run the script by double clicking on ms_rewards_farmer.py

**Comment by AlexyGalaxy** [comment]
> needs update! client socket handshake failed ssl errors not finishing mobile or should say start mobile search


Uninstall and install using this

README How to Install:
Install zip from GitHub: https://github.com/charlesbel/Microsoft-Rewards-Farmer

Install Python https://www.python.org/downloads/
Select custom installation, change nothing hit yes until installed.

Open Microsoft-Rewards-Farmer-master, move requirements.txt to C:\Users\Alex

Open command prompt. win + R>CMD, then type (without quotes): 'pip install -r requirements.txt' Press enter

Intall Google Chrome.

Install ChromeDriver from https://chromedriver.chromium.org/downloads
Place the file in X:\Windows (X as your Windows disk letter)

Edit the accounts.json.sample with your accounts credentials and rename it by removing .sample at the end
If you want to add more than one account, the syntax is the following :
[
{
"username": "Your Email",
"password": "Your Password"
},
{
"username": "Your Email",
"password": "Your Password"
}
]

How to Fix Mobile:
Comment out around line 134-138 with double quotes above and below
""
# Refresh page
browser.get('https://bing.com/')
# Wait 5 seconds
time.sleep(10)
#Update Counter
""

How to run Script:
Run the script by double clicking on ms_rewards_farmer.py
