### ISSUE TITLE
mobile search not working anymore

### ISSUE THREAD

**Issue by inverspe** [charlesbel/Microsoft-Rewards-Farmer#132]
you should fix this thank you in advance

**Comment by Ector70** [comment]
Same problem.

**Comment by inverspe** [comment]
> Same problem.

did u fix it?

**Comment by inverspe** [comment]
> Same problem.

remove line 86 mobile search works for me now

checkBingLogin(browser, isMobile)

**Comment by inverspe** [comment]
> Same problem.

remove line 86 

checkBingLogin(browser, isMobile)

**Comment by AlexyGalaxy** [comment]
> > Same problem.
> 
> remove line 86
> 
> checkBingLogin(browser, isMobile)

> Same problem.

DO NOT COMMENT OUT LINE 86 if you do POINTS_COUNTER will not work properly. 

Instead try this:
-How to Fix Mobile:
Comment out around line 134-138 with double quotes above and below
""
#Refresh page
browser.get('https://bing.com/')
#Wait 5 seconds
time.sleep(10)
#Update Counter
""

-How to run Script:

**Comment by josedavidrp** [comment]
> > > Same problem.
> > 
> > 
> > remove line 86
> > checkBingLogin(browser, isMobile)
> 
> DO NOT COMMENT OUT LINE 86 if you do POINTS_COUNTER will not work properly.
> 
> **Instead try this:** -How to Fix Mobile: Comment out around line 134-137 with three double quotes above and below """ #Refresh page browser.get('https://bing.com/') #Wait 5 seconds time.sleep(10) """

Hi, do you have any problem with mobile searches? Im using your fork but in headless mode it will loop in the first search. But when I make it with the chrome tab open i can make it work closing the bing full screen cookies notice. Maybe thats the issue in headless mode and you could check it to fix it, thanks.

**Comment by AlexyGalaxy** [comment]
There is an issue sometimes with mobile and desktop searches. I put a re-try function for both. If the re-try does not work I restart the script and it seems to work.

Il'll look into it more.

**Comment by AlexyGalaxy** [comment]
Found the issue. Wehn trying to complete mobile searches the user was not fully logged in.

Code has been updated.

If you would like to check it out my github link is: https://github.com/AlexyGalaxy/Microsoft-Rewards-Farmer

**Comment by josedavidrp** [comment]
> Found the issue. Wehn trying to complete mobile searches the user was not fully logged in.
> 
> Code has been updated.
> 
> If you would like to check it out my github link is: https://github.com/AlexyGalaxy/Microsoft-Rewards-Farmer

Perfect! I'll try it today, thanks for your fork :)

**Comment by charlesbel** [comment]
Fixed with v3.0 #188
