### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by BigYty** [charlesbel/Microsoft-Rewards-Farmer#133]
Traceback (most recent call last):
  File "ms_rewards_farmer.py", line 752, in <module>
    ACCOUNTS = json.load(open(account_path, "r"))
  File "/usr/lib64/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 6 column 5 (char 94)

**Comment by AlexyGalaxy** [comment]
> Traceback (most recent call last): File "ms_rewards_farmer.py", line 752, in ACCOUNTS = json.load(open(account_path, "r")) File "/usr/lib64/python3.6/json/**init**.py", line 299, in load parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw) File "/usr/lib64/python3.6/json/**init**.py", line 354, in loads return _default_decoder.decode(s) File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "/usr/lib64/python3.6/json/decoder.py", line 355, in raw_decode obj, end = self.scan_once(s, idx) json.decoder.JSONDecodeError: Expecting ',' delimiter: line 6 column 5 (char 94)

Make sure you have manually logged into your bing rewards account and clicked join microsoft rewards to show you the "Microsoft Bing Dashboard".

If that doesnt work, comment out the following lines of code around line 31 and 32 to disable headless mode and watch the script work.

if headless_mode : #comment out to disable headless mode (makes window visable)
options.add_argument("--headless")
