### ISSUE TITLE
[BUG] Newly created accounts is not work.

### ISSUE THREAD

**Issue by syunohito** [charlesbel/Microsoft-Rewards-Farmer#135]
The old account I created worked normally, but the newly created account is not working with a traceback error.

**Comment by syunohito** [comment]
Traceback (most recent call last):
  File "C:\Users\ｘ\Pictures\Microsoft-Rewards-Farmer-master\ms_rewards_farmer.py", line 779, in <module>
    waitUntilVisible(browser, By.XPATH, '//*[@id="navs"]/div/div/div/div/div[4]/a', 20)
  File "C:\Users\ｘ\Pictures\Microsoft-Rewards-Farmer-master\ms_rewards_farmer.py", line 160, in waitUntilVisible
    WebDriverWait(browser, time_to_wait).until(ec.visibility_of_element_located((by_, selector)))
  File "C:\Users\ｘ\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 87, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:

**Comment by AlexyGalaxy** [comment]
> The old account I created worked normally, but the newly created account is not working with a traceback error.

Make sure you have manually logged into your bing rewards account and clicked join microsoft rewards to show you the "Microsoft Bing Dashboard".

If that doesnt work, comment out the following lines of code around line 31 and 32 to diable headless mode and watch the script work.

if headless_mode : #comment out to disable headless mode (makes window visable)
options.add_argument("--headless")

If this did not work I can also post a simple and updated README that you can follow for installation.

**Comment by charlesbel** [comment]
Fixed with v3.0 #188
