### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by GreenSussy** [charlesbel/Microsoft-Rewards-Farmer#137]
I have used this program before, with no problem. That was around August 2022. I decided to come back now and updated python to 3.11. Installed all the requirements, and the chrome web driver is in the correct location and updated.

The current problem is that when I run the script, the command prompt opens and immediately closes. 

Any fixes?

**Comment by thearyadev** [comment]
Hard to help you without more information. 

but you can try this: 
1. run it with python3.10 or older. Cross compatibility between python versions isn't guaranteed. 
2. open your terminal, run `python ms_rewards_farmer.py`. This will show the error instead of closing the terminal window

**Comment by AlexyGalaxy** [comment]
> I have used this program before, with no problem. That was around August 2022. I decided to come back now and updated python to 3.11. Installed all the requirements, and the chrome web driver is in the correct location and updated.
> 
> The current problem is that when I run the script, the command prompt opens and immediately closes.
> 
> Any fixes?

You need to check your accounts file to make sure it has correct syntax and check your main .py file to make sure it has correct syntax. If you have something out of place the script will do this.

Or uninstall and redownload. Here is a README I have created for this project to help. Good Luck.

README How to Install:
-Install zip from GitHub: https://github.com/charlesbel/Microsoft-Rewards-Farmer

-Install Python https://www.python.org/downloads/
Select custom installation, change nothing hit yes until installed.

-Open Microsoft-Rewards-Farmer-master, move requirements.txt to C:\Users\Alex

-Open command prompt. win + R>CMD, then type (without quotes): 'pip install -r requirements.txt' Press enter

-Intall Google Chrome.

-Install ChromeDriver from https://chromedriver.chromium.org/downloads
Place the file in X:\Windows (X as your Windows disk letter)

-Edit the accounts.json.sample with your accounts credentials and rename it by removing .sample at the end
If you want to add more than one account, the syntax is the following :
[
{
"username": "Your Email",
"password": "Your Password"
},
{
"username": "Your Email",
"password": "Your Password"
}
]

-How to Fix Mobile:
Comment out around line 134-138 with double quotes above and below
""
# Refresh page
browser.get('https://bing.com/')
# Wait 5 seconds
time.sleep(10)
#Update Counter
""

-How to run Script:
Run the script by double clicking on ms_rewards_farmer.py

**Comment by inverspe** [comment]
> > I have used this program before, with no problem. That was around August 2022. I decided to come back now and updated python to 3.11. Installed all the requirements, and the chrome web driver is in the correct location and updated.
> > The current problem is that when I run the script, the command prompt opens and immediately closes.
> > Any fixes?
> 
> You need to check your accounts file to make sure it has correct syntax and check your main .py file to make sure it has correct syntax. If you have something out of place the script will do this. Id reccomend using Visual Studios Code. Once open it should recommend you to install a python extention. Then Visual Studios Code should recomend changes to help make the script run.
> 
> Or uninstall and redownload. Here is a README I have created for this project to help. Good Luck.
> 
> **README How to Install:** -Install zip from GitHub: https://github.com/charlesbel/Microsoft-Rewards-Farmer
> 
> -Install Python https://www.python.org/downloads/ Select custom installation, change nothing hit yes until installed.
> 
> -Open Microsoft-Rewards-Farmer-master, move requirements.txt to C:\Users\Alex
> 
> -Open command prompt. win + R>CMD, then type (without quotes): 'pip install -r requirements.txt' Press enter
> 
> -Intall Google Chrome.
> 
> -Install ChromeDriver from https://chromedriver.chromium.org/downloads Place the file in X:\Windows (X as your Windows disk letter)
> 
> -Edit the accounts.json.sample with your accounts credentials and rename it by removing .sample at the end If you want to add more than one account, the syntax is the following : [ { "username": "Your Email", "password": "Your Password" }, { "username": "Your Email", "password": "Your Password" } ]
> 
> -How to Fix Mobile: Comment out around line 134-137 with three double quotes above and below """ #Refresh page browser.get('https://bing.com/') #Wait 5 seconds time.sleep(10) """
> 
> -How to run Script: Run the script by double clicking on ms_rewards_farmer.py

show picture

**Comment by AlexyGalaxy** [comment]
> > > I have used this program before, with no problem. That was around August 2022. I decided to come back now and updated python to 3.11. Installed all the requirements, and the chrome web driver is in the correct location and updated.
> > > The current problem is that when I run the script, the command prompt opens and immediately closes.
> > > Any fixes?
> > 
> > 
> > You need to check your accounts file to make sure it has correct syntax and check your main .py file to make sure it has correct syntax. If you have something out of place the script will do this. Id reccomend using Visual Studios Code. Once open it should recommend you to install a python extention. Then Visual Studios Code should recomend changes to help make the script run.
> > Or uninstall and redownload. Here is a README I have created for this project to help. Good Luck.
> > **README How to Install:** -Install zip from GitHub: https://github.com/charlesbel/Microsoft-Rewards-Farmer
> > -Install Python https://www.python.org/downloads/ Select custom installation, change nothing hit yes until installed.
> > -Open Microsoft-Rewards-Farmer-master, move requirements.txt to C:\Users\Alex
> > -Open command prompt. win + R>CMD, then type (without quotes): 'pip install -r requirements.txt' Press enter
> > -Intall Google Chrome.
> > -Install ChromeDriver from https://chromedriver.chromium.org/downloads Place the file in X:\Windows (X as your Windows disk letter)
> > -Edit the accounts.json.sample with your accounts credentials and rename it by removing .sample at the end If you want to add more than one account, the syntax is the following : [ { "username": "Your Email", "password": "Your Password" }, { "username": "Your Email", "password": "Your Password" } ]
> > -How to Fix Mobile: Comment out around line 134-137 with three double quotes above and below """ #Refresh page browser.get('https://bing.com/') #Wait 5 seconds time.sleep(10) """
> > -How to run Script: Run the script by double clicking on ms_rewards_farmer.py
> 
> show picture
Not sure what this means...

I offered a solution to the issue.  Please refrain from commenting if you are not going to offer help to those with issues relating to this project. Also spam posting another project is not a solution to anyone's issue.

**Comment by inverspe** [comment]
> > > > I have used this program before, with no problem. That was around August 2022. I decided to come back now and updated python to 3.11. Installed all the requirements, and the chrome web driver is in the correct location and updated.
> > > > The current problem is that when I run the script, the command prompt opens and immediately closes.
> > > > Any fixes?
> > > 
> > > 
> > > You need to check your accounts file to make sure it has correct syntax and check your main .py file to make sure it has correct syntax. If you have something out of place the script will do this. Id reccomend using Visual Studios Code. Once open it should recommend you to install a python extention. Then Visual Studios Code should recomend changes to help make the script run.
> > > Or uninstall and redownload. Here is a README I have created for this project to help. Good Luck.
> > > **README How to Install:** -Install zip from GitHub: https://github.com/charlesbel/Microsoft-Rewards-Farmer
> > > -Install Python https://www.python.org/downloads/ Select custom installation, change nothing hit yes until installed.
> > > -Open Microsoft-Rewards-Farmer-master, move requirements.txt to C:\Users\Alex
> > > -Open command prompt. win + R>CMD, then type (without quotes): 'pip install -r requirements.txt' Press enter
> > > -Intall Google Chrome.
> > > -Install ChromeDriver from https://chromedriver.chromium.org/downloads Place the file in X:\Windows (X as your Windows disk letter)
> > > -Edit the accounts.json.sample with your accounts credentials and rename it by removing .sample at the end If you want to add more than one account, the syntax is the following : [ { "username": "Your Email", "password": "Your Password" }, { "username": "Your Email", "password": "Your Password" } ]
> > > -How to Fix Mobile: Comment out around line 134-137 with three double quotes above and below """ #Refresh page browser.get('https://bing.com/') #Wait 5 seconds time.sleep(10) """
> > > -How to run Script: Run the script by double clicking on ms_rewards_farmer.py
> > 
> > 
> > show picture
> 
> Not sure what this means... I posted an updated README
> 
> I offered a solution to the issue. Please refrain from commenting if you are not going to offer help to those with issues relating to this project. Also spam posting another project is not a solution to anyone's issue.

i removed line 134 to 137  and replaced it with your fix every time I run the app it crashes instantly

**Comment by AlexyGalaxy** [comment]
The lines you need to comment out are different than mine because I have made serval changes to my code. If you are using the current version of the code from this git hub repository, try to comment out lines 130-134.

    #Wait 2 seconds
    time.sleep(2)
    # Refresh page
    browser.get('https://bing.com/')
    # Wait 5 seconds

If you are still having issues I suggest redownloading the code and reinstalling everything.

**Comment by charlesbel** [comment]
Fixed with v3.0 #188
