### ISSUE TITLE
Error Please Help

### ISSUE THREAD

**Issue by Pratikk1337** [charlesbel/Microsoft-Rewards-Farmer#138]
Traceback (most recent call last):
  File "ms_rewards_farmer.py", line 773, in <module>
    login(browser, account['username'], account['password'])
  File "ms_rewards_farmer.py", line 58, in login
    browser.find_element(By.ID, 'idSIButton9').click()
  File "C:\Users\PRATIK\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\PRATIK\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\PRATIK\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\PRATIK\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: headless chrome=108.0.5359.125)
![vdvdvdv](https://user-images.githubusercontent.com/96905738/210617344-f7e71d74-ec17-4957-819e-9f33754b16b3.PNG)

**Comment by thearyadev** [comment]
Hi. It seems like this project has been abandoned. 
I've been working on this, and I'm looking for testers. 

https://github.com/thearyadev/MSRF

**Comment by AlexyGalaxy** [comment]
Have you have manually logged into your bing rewards account and clicked join microsoft rewards to show you the "Microsoft bing Dashboard". If you havent done this the script has issues.

Or go to around line 31 and 32 and comment out these lines using # to disable headless mode, it allows you to watch the script as it works.
#if headless_mode : #comment out to disable headless mode (makes window visable) 
        #options.add_argument("--headless")

**Comment by AlexyGalaxy** [comment]
> Traceback (most recent call last): File "ms_rewards_farmer.py", line 773, in login(browser, account['username'], account['password']) File "ms_rewards_farmer.py", line 58, in login browser.find_element(By.ID, 'idSIButton9').click() File "C:\Users\PRATIK\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click self._execute(Command.CLICK_ELEMENT) File "C:\Users\PRATIK\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute return self._parent.execute(command, params) File "C:\Users\PRATIK\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute self.error_handler.check_response(response) File "C:\Users\PRATIK\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response raise exception_class(message, screen, stacktrace) selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable (Session info: headless chrome=108.0.5359.125) ![vdvdvdv](https://user-images.githubusercontent.com/96905738/210617344-f7e71d74-ec17-4957-819e-9f33754b16b3.PNG)

 if headless_mode : #comment out to disable headless mode (makes window visable) 
        options.add_argument("--headless")
