### ISSUE TITLE
install txt

### ISSUE THREAD

**Issue by Cybern9ne** [charlesbel/Microsoft-Rewards-Farmer#139]
do i use pyton or cmd to install the requirements.txt file, just having trouble if you can post a image on how to install that would be legit thanks,

**Comment by thearyadev** [comment]
Hi. It seems like this project has been abandoned. 
I've been working on this, and I'm looking for testers. 

https://github.com/thearyadev/MSRF

**Comment by AlexyGalaxy** [comment]
> do i use pyton or cmd to install the requirements.txt file, just having trouble if you can post a image on how to install that would be legit thanks,

I made my own updated readme for this project. Let me know if you need additional help.
**README
How to Install:**
-Install zip from GitHub: https://github.com/charlesbel/Microsoft-Rewards-Farmer

-Install Python https://www.python.org/downloads/
	Select custom installation, change nothing hit yes until installed. 

-Open Microsoft-Rewards-Farmer-master, move requirements.txt to C:\Users\Alex

-Open command prompt. win + R>CMD, then type (without quotes): 'pip install -r requirements.txt' 	Press enter

-Intall Google Chrome.

-Install ChromeDriver from https://chromedriver.chromium.org/downloads
	Place the file in X:\Windows (X as your Windows disk letter)

-Edit the accounts.json.sample with your accounts credentials and rename it by removing .sample at the end
If you want to add more than one account, the syntax is the following :
[
    {
        "username": "Your Email",
        "password": "Your Password"
    },
    {
        "username": "Your Email",
        "password": "Your Password"
    }
]

-How to run Script:
Run the script by double clicking on ms_rewards_farmer.py

-How to Fix Mobile:
Comment out around line 134-138 with double quotes above and below 
    ""
    # Refresh page
    browser.get('https://bing.com/')
    # Wait 5 seconds
    time.sleep(10)
    #Update Counter
    ""
