### ISSUE TITLE
[BUG] Daily Set Quiz Skipped (Solution Found)

### ISSUE THREAD

**Issue by AlexyGalaxy** [charlesbel/Microsoft-Rewards-Farmer#141]
Yesterday The script was skipping over the "Daily Set Quiz" (the second or middle card). I am not sure why. The answers were A B C with 7 total questions. I disabled Headless mode and watched the script answer the first question in the quiz then reload back to the dashboard. I am guessing that was the script skipping the quiz and continuing on with the script?

Anyone know a proper fix to the completeDailySetQuiz function?

**Comment by inverspe** [comment]
have u fixed it yet also srry for posting an alternative

**Comment by AlexyGalaxy** [comment]
No the script seems to always skip the second daily set pannel Quiz. 

Today there is a quiz that has 3 questions and 3 answers per question. (ABC)
  
The script trys to run the function completeDailySetVariableActivity but fails to complete the pannel. 

I am trying to figure out a soultion but nothing has worked so far.

**Comment by AlexyGalaxy** [comment]
The solution posted above did not work the very next day. I am going to look at it again to try to figure out why. 

If anyone has a solution please post it here.

**Comment by AlexyGalaxy** [comment]
I forked this project and uploaded my current working version that will complete all searches and punch cards. Also made the README even more simple to understand.

https://github.com/AlexyGalaxy/Microsoft-Rewards-Farmer

**Comment by AlexyGalaxy** [comment]
The hard code above will not work with today's daily quiz because it has 7 questions. Looking into a solution. I will post an update here and update my github when found and working.

**Comment by charlesbel** [comment]
Fixed with v3.0 #188
