### ISSUE TITLE
[Exception] Farmer - Index was outside the bounds of the array.   

### ISSUE THREAD

**Issue by GuyGieri** [charlesbel/Microsoft-Rewards-Farmer#148]
Hi, Ive been using the farmer with one account for about a month and all was well. Recently I added 3 more accounts to make 4 in total and started getting an error on my main/first one.

![image](https://user-images.githubusercontent.com/113925058/216385904-fa2602d5-8370-41e4-8c05-9b019d629424.png)

It will get about halfway and then give me this error, but all of the other accounts work just fine. Any advice?

**Comment by GuyGieri** [comment]
Better photo: 
![image](https://user-images.githubusercontent.com/113925058/216386169-20549a49-4a6e-4a3d-88a9-bba203db7e22.png)

**Comment by Tom60chat** [comment]
Hey i'm Tom from Microsoft-Rewards-Farmer-Sharp,

This seam you published an issue on the wrong repositories from your screenshot.

I invite you to go to https://github.com/Tom60chat/Microsoft-Rewards-Farmer-Sharp and open or search for an existing issue.
