### ISSUE TITLE
Microsoft Rewards Farmer not Working

### ISSUE THREAD

**Issue by pro7777777777** [charlesbel/Microsoft-Rewards-Farmer#149]
![MS Farmer Error](https://user-images.githubusercontent.com/124313916/216468863-726a501e-0b04-4c1e-ba36-60179a81996d.png)

**Comment by AlexyGalaxy** [comment]
Has the script ever run correctly for you or is this your first run?
Are you on Mac?
Did you install everything from the requirements.txt?

I think the issue might be with the cromedriver you are using. the readme states

Install requirements with the following command :
```
pip install -r requirements.txt
```
Make sure you have Chrome installed
Install ChromeDriver :
Windows :

- Download Chrome WebDriver : https://chromedriver.chromium.org/downloads
- Place the file in X:\Windows (X as your Windows disk let

MacOS or Linux :
```
apt install chromium-chromedriver
```

**Comment by pro7777777777** [comment]
I am on Mac and. I did install everything from requirements.txt but the script has never run correctly it always came back with an error

**Comment by AlexyGalaxy** [comment]
I am not a mac user but it does seem that there is an issue with your chomedriver. I would try to uninstall it and install a different version.

**Comment by pro7777777777** [comment]
Thanks it worked

**Comment by AlexyGalaxy** [comment]
Glad to help. I have uploaded an updated version of this scrip to my github. It allows for more quizes to be completed as bing rewards keeps updating. I also added timers and counters and im working on adding a logger and error logger. 
```
If you would like to check it out my github link is: https://github.com/AlexyGalaxy/Microsoft-Rewards-Farmer
```

**Comment by beatle1987** [comment]
I had the same issue, but reinstalling chrome /chromedirver did not change

**Comment by AlexyGalaxy** [comment]
Please post a picture of your cmd window with the error message.

**Comment by beatle1987** [comment]
Fixed it. Was a combination of two errors. Updating the chrome driver and had to verify my phone number
