### ISSUE TITLE
One minute Quiz is not being completed

### ISSUE THREAD

**Issue by pro7777777777** [charlesbel/Microsoft-Rewards-Farmer#150]
The one minute Quiz is not being completed

![image](https://user-images.githubusercontent.com/124313916/216796522-f3c8b781-e22c-428d-bd5b-6670521bfc8a.png)

**Comment by AlexyGalaxy** [comment]
I have uploaded an updated version of this scrip to my github. It allows for more quizes to be completed as bing rewards keeps updating. I also added timers and counters and im working on adding a logger and error logger.

If you would like to check it out my github link is: https://github.com/AlexyGalaxy/Microsoft-Rewards-Farmer

**Comment by pro7777777777** [comment]
TYSM it works

**Comment by pro7777777777** [comment]
hi now I am getting the error [ERROR] An Error has Occured While Trying to Wait Until Visible.

**Comment by charlesbel** [comment]
Fixed with v3.0 #188
