### ISSUE TITLE
[BUG][STUCK] Stuck in "[LOGIN] Ensuring login on Bing..."

### ISSUE THREAD

**Issue by Jamramir** [charlesbel/Microsoft-Rewards-Farmer#156]
I put the credentials in the file and reran the python script. It gets stuck here. I left it for an hour, and it's still stuck.

![imagen](https://user-images.githubusercontent.com/93263583/218285192-6ac4e2c2-a525-438a-8e7e-9ff62bb34cc7.png)

**Comment by sustract** [comment]
How did you solved that? I'm on the same point.
