### ISSUE TITLE
The Script Wont Open 

### ISSUE THREAD

**Issue by xIBinkyIx** [charlesbel/Microsoft-Rewards-Farmer#157]
I've looked through the issues that looked like they would be able to help but unfortunately not. I've moved the files to where you have said (the requirements.txt and chrome driver) I've installed the requirements and as i go to open the python file it shows a window for a spilt second then just disappears 

https://user-images.githubusercontent.com/122353512/218311011-be2452c0-5223-4f95-a796-1865178a1b40.mp4

**Comment by AlexyGalaxy** [comment]
I have uploaded an updated version of this scrip to my github. It allows for more quizes to be completed as bing rewards keeps updating. I also added timers and counters and im working on adding a logger and error logger.

If you would like to check it out my github link is: https://github.com/AlexyGalaxy/Microsoft-Rewards-Farmer

If you have any issues comment below and I can try to help you. New issues pop up if you are located in a different region other than the US.

**Comment by xIBinkyIx** [comment]
I've looked through the issues that looked like they would be able to help but unfortunately not. I've moved the files to where you have said (the requirements.txt and chrome driver) I've installed the requirements and as i go to open the python file it shows a window for a spilt second then just disappears

**Comment by Xyl3ntHacks** [comment]
> I've looked through the issues that looked like they would be able to help but unfortunately not. I've moved the files to where you have said (the requirements.txt and chrome driver) I've installed the requirements and as i go to open the python file it shows a window for a spilt second then just disappears

**Comment by Xyl3ntHacks** [comment]
Have you made sure to add the Chrome driver path to your environment variable. If not this tutorial will help https://www.youtube.com/watch?v=dz59GsdvUF8&t=132s

**Comment by xIBinkyIx** [comment]
Hello, so sorry for the late reply but I have looked into everything that
you have said and even with the code you gave me to put at the bottom of
the script it still does not stay open for me to see anything. I have
installed the requirements.txt file successfully as well as the
chromedriver and it still does not run properly or even stay open for
anything to show. The link I am using to download your script is this link
<https://github.com/AlexyGalaxy/Microsoft-Rewards-Farmer> which seems like
the newest one. I appreciate the lengths you are going to, to help me. I am
truly sorry for the inconvenience however if there is anything else i can
try to get it to work please do let me know, i would love to use your
script as i'm sure many other people would. Would having a visual step by
step of installation and use be a plause idea for you to help me, and
possibly others?

**Comment by AlexyGalaxy** [comment]
If you are using the script from that link the script will stay open when ran. download Visual Studio Code (VSC). Set up your accounts in the account file. Then open the script file with VSC. When VSC is open press the play arrow at the top right to start the script.

**Comment by xIBinkyIx** [comment]
this is the error it gave me when running it through vsc

line 4, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by xIBinkyIx** [comment]
It was a start hahaha.

I have tried doing what you said by installing the requirements.txt they
way you said, and as i did that it said to me that it all installed
successfully.
However, as i rna the python file, it did the same thing that it always
does (opens then closes with me not being able to see anything) so I tried
seeing if the error the VSC gave would change, and to no avail the error in
VSC was still the same

**Comment by AlexyGalaxy** [comment]
What operating system are you using Windows 10, 11, Mac, Linux?
Do you have google chrome installed
Did you install ChromeDriver?

**Comment by xIBinkyIx** [comment]
I’m using windows as my OS and i have both google chrome and ChromeDriver
installed

**Comment by AlexyGalaxy** [comment]
if yes to all, I'd recommend uninstall python, delete the MS Farmer, and uninstall/delete ChromeDriver. Then reinstall/download all of it starting with python, MS Farmer, ChromeDriver. Also install an older verion of crhomeDriver just incase.
