### ISSUE TITLE
[BUG] Unknown Error:entry_impl.cc(1082)] No file for 80000029

### ISSUE THREAD

**Issue by AlexyGalaxy** [charlesbel/Microsoft-Rewards-Farmer#158]
Not sure what causes this error but It seems to happen during desktop searches. As you can see searches do complete. I would like to solve this issue but when searched online people say restart the browser. So im not sure if its a coding issue.
![random eror](https://user-images.githubusercontent.com/86795638/218536240-511569c4-aadc-4822-8c83-86e943aa90db.JPG)

**Comment by AlexyGalaxy** [comment]
This error poped up again today during the daily set and in desktop searches. Only happened with the first account run and stopped after 8/34 bing seaches.
![error](https://user-images.githubusercontent.com/86795638/219420504-ead9b8d9-7cc4-4a5d-bd60-91138a4c5f13.JPG)

**Comment by AlexyGalaxy** [comment]
This bug does not stop the script from running; it is just annoying and should be ignored.

**Comment by charlesbel** [comment]
Fixed with v3.0 #188
