### ISSUE TITLE
It is very slow[BUG]

### ISSUE THREAD

**Issue by armaanbrar14** [charlesbel/Microsoft-Rewards-Farmer#165]
its very slow. what i do

**Comment by pearlheartgtr** [comment]
Open the MS_Rewards_Farmer.py file in notepad (I use Notepad++ -- it's free, the lines are numbered to make it easier).
Go to line #43 -- Sleep timer. I changed it to 30, 120 on all of the lines (43, 44, 45). Makes it a bit faster. Not blazing, but it doesn't take an hour and a half to 2 hours to run 4 accounts anymore. Hit save and you're ready to go. 

I hope this helps!

**Comment by AlexyGalaxy** [comment]
Becareful. The faster your MS Farmer the more likely your accounts will get locked/suspended/banned. The timers are put there to ensure this does not happen. You can get 12 accounts to run in about 8-9 hours with the current settings. About 30 mins per account with 5-6 mins in between each run.

**Comment by AlexyGalaxy** [comment]
Id recommend using Visual Studio Code, It is free and the console outputs with color
![image](https://user-images.githubusercontent.com/86795638/224325534-7e847356-dc30-4391-a641-f61c96cefe43.png)

**Comment by charlesbel** [comment]
Fixed with v3.0 #188
