### ISSUE TITLE
Multi-Account Management - How

### ISSUE THREAD

**Issue by raphalation** [charlesbel/Microsoft-Rewards-Farmer#17]
In the features list, there is Multi-Account Management.

How do you use this? I can't see a place to add an additional account details

**Comment by charlesbel** [comment]
I think you don't know a lot about python lists...
The ACCCOUNTS variable looks like this with 1 account :
```
ACCOUNTS = [
    {
        "username": "Your Email",
        "password": "Your Password"
    }
]
```
So if you want 2 accounts you have just to make this :
```
ACCOUNTS = [
    {
        "username": "Your Email",
        "password": "Your Password"
    },
    {
        "username": "Your Email 2",
        "password": "Your Password 2"
    }
]
```

**Comment by raphalation** [comment]
great thanks
