### ISSUE TITLE
[BUG] stuck on stay signed in

### ISSUE THREAD

**Issue by timewolf** [charlesbel/Microsoft-Rewards-Farmer#171]
All worked fine since yesterday, today it stuck after password, on the "stay signed in" window

If I try manually with edge/chrome it works fine

<img width="321" alt="image" src="https://user-images.githubusercontent.com/44172693/230483901-188ddf82-6541-43d0-a2ce-f761a2fa71c6.png">

**Comment by GuyGieri** [comment]
Im getting a similar issue where it gets stuck on "Ensuring login on bing" unless I reload the tab out of headless mode

**Comment by charlesbel** [comment]
Fixed with v3.0 #188
