### ISSUE TITLE
How to start farming?

### ISSUE THREAD

**Issue by Qgt03** [charlesbel/Microsoft-Rewards-Farmer#173]
When I open the script, it opens for a second and immediately shuts down. I did everything according to the tutorial.

**Comment by Qgt03** [comment]
I solved the problem, but after logging in and showing the number of my points, I was given this and a new line began. 
![Снимок экрана 2023-04-11 194340](https://user-images.githubusercontent.com/130470120/231232319-d5c21601-cf37-4aea-aa4e-149205bb87be.png)

**Comment by charlesbel** [comment]
Fixed with v3.0 #188
