### ISSUE TITLE
5 of my accounts were permanently suspended within 3 days.

### ISSUE THREAD

**Issue by AlexyGalaxy** [charlesbel/Microsoft-Rewards-Farmer#178]
Not sure why this is happening but 5 of my accounts have been suspended within the last 3 days. Please post below if you are also experiencing this. Not sure if MAC address is being tracked or IP.

**Comment by tastybiscuit98** [comment]
This happened to all my accounts last month. Whenever I tried to claim a reward, it just said:

''There's an issue with your account or order. Please contact Microsoft Rewards customer support for assistance.''

I later got a new phone number and created a new account, but the same issue occurred when I tried to redeem a reward. The weird thing is that it still lets me do the quiz and earn points. I just assumed I got IP banned, so I gave up. Is the same thing occurring with you?

**Comment by OTPEspectral** [comment]
Same here, got banned like 8 out of 13 accounts, used the same number in more than 5 accounts, so im not sure if thats the problem, but seems like they are taking action.

**Comment by AlexyGalaxy** [comment]
all 14 of my accounts were banned. I used 4 per phone number and 3 on 2 phone numbers. I used them for about 3 months. Not sure what happened. Maybe there needs to be a longer delay between login for each account. Maybe the entire process needs to be slowed down with longer sleep timers within the functions.

**Comment by OTPEspectral** [comment]
I've been using the same script but faster timers, so i don't think the timers are the problem here. Maybe adding a long timer between accounts and IP/MAC changer?

**Comment by AlexyGalaxy** [comment]
I have no clue how to do that

**Comment by lollogiaco** [comment]
chrome got updated , so I updated chromedriver but it says this:

"Traceback (most recent call last):
  File "C:\Users\loren\OneDrive\Documenti\GitHub\Microsoft-Rewards-Farmer\ms_rewards_farmer.py", line 1544, in <module>
    browser.get(BASE_URL)
AttributeError: 'NoneType' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\loren\OneDrive\Documenti\GitHub\Microsoft-Rewards-Farmer\ms_rewards_farmer.py", line 1547, in <module>
    FA.write('\n[ERROR] Could not Loading https://rewards.bing.com/.')
ValueError: I/O operation on closed file.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\loren\OneDrive\Documenti\GitHub\Microsoft-Rewards-Farmer\ms_rewards_farmer.py", line 1801, in <module>
    browser.quit()
AttributeError: 'NoneType' object has no attribute 'quit' "

can sm1 help?

**Comment by Dunge** [comment]
Does everyone who got their account banned was using the software on multiple accounts? I was only using one and I'm still good, but I stopped using the script since a few days until we get more information. Would love to hear more details from other people.

@lollogiaco your question is unrelated to this topic and should have been posted in a different thread. But just update your chrome-driver to match your chrome version. Try `pip install --upgrade webdriver-manager`

**Comment by shopbuy11** [comment]
> Does everyone who got their account banned was using the software on multiple accounts? I was only using one and I'm still good, but I stopped using the script since a few days until we get more information. Would love to hear more details from other people.
> 
> @lollogiaco your question is unrelated to this topic and should have been posted in a different thread. But just update your chrome-driver to match your chrome version. Try `pip install --upgrade webdriver-manager`

I have been using 5 accounts for years without issue.  A few years back, they did reach out and I told them that they are just different family members using the same computer.

**Comment by Ector70** [comment]
> 

Tell us if you resolve with support

**Comment by shopbuy11** [comment]
No reply so far.  Not holding my breath.  Feel free to submit support request too and see if you get response...

**Comment by tastybiscuit98** [comment]
UPDATE: It seems my accounts were unbanned somehow (I didn't speak to customer service because I heard they ban you forever if you do that), and I was able to claim all rewards. 

I was able to sign in and get points manually, though, but it seems the bot will not work now due to the old or new ChromeDriver. Perhaps Microsoft has finally cracked down on automated bots?
