### ISSUE TITLE
[BUG] various code lines have ^^^^^^^^^^^ under them / timeout / pool / return self

### ISSUE THREAD

**Issue by Sanntraker** [charlesbel/Microsoft-Rewards-Farmer#179]
I am not good with coding.

The program worked for months before this. I think these errors started with the chrome version changing from 112 to 114 through autoupdate. I dont know how to downgrade and dont really want to. I downloaded the 114 chromedriver to replace the 112 chromedriver in c\windows. I have selenium 3.14.1.

Please help!

<img width="602" alt="error" src="https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/135379124/66214211-498a-4042-8863-3ab2e47b879a">

**Comment by charlesbel** [comment]
Fixed with v3.0 #188
