### ISSUE TITLE
All accounts banned

### ISSUE THREAD

**Issue by Ector70** [charlesbel/Microsoft-Rewards-Farmer#181]
They banned 5 accounts a week ago, then I created new ones, but today same ban for them. Is there something I can do? It's the first time with all this ban.

**Comment by alessiouw** [comment]
same here.

**Comment by Gitzzly** [comment]
How do you do this? Are you using different VPNs?

**Comment by alessiouw** [comment]
you can use protonvpn (if you have a cli machine you can use protonvpn-cli). Also you can include in the script an automatic connection to the different vpn servers offered by proton (I use the free verision, which is limited to about 190 servers in EU, Japan and US).
I use the command protonvpn-cli c -r (to connect to a random VPN server, then the script starts)

**Comment by Ector70** [comment]
How should I do with windows?

**Comment by kenny070287** [comment]
@alessiouw just curious, im interested to setup a linux VM to try ou the protonvpn-cli.

1. will this be safer than not using vpn? like how long have you run this stuff?
2. where do you insert the command, if you dont mind me asking
3. do you use the same location for each account, or everything is randomised?

**Comment by gittyupcowboy** [comment]
> I think there's no protonvpn CLI for windows. There's for sure the GUI version, you can automate it somehow with Task Scheduler

You might be able to do it on Windows 10/11 using Windows Subsystem for Linux  WSL) 10/11. https://learn.microsoft.com/en-us/windows/wsl/install 

Your mileage may vary (I recommend the Ubuntu WSL flavor if you're new to linux/WSL).

**Comment by kenny070287** [comment]
Well I managed to setup proton vpn and uses a script to change address when switching account. However I still got banned. Probably because same device is detected or something.

In any case, I'm running this legit now, unless a surefire way is discovered.
