### ISSUE TITLE
[Feature Request] Increase wait time for 2FA prompt

### ISSUE THREAD

**Issue by gh0sti** [charlesbel/Microsoft-Rewards-Farmer#190]
One thing that will make it easier for 2FA is to increase the wait time. I am currently using MS Authenticator app and I have to pop open my phone find the right 2 digit code then faceID to approve. I think the current time out is too short where I have to race the clock to get the 2FA prompt in quick before the window closes out and stops the script b/c it didn't get the 2FA in time. I was able to eventually get 2FA secured and session stored for future script runs.

**Comment by Kurotaku-sama** [comment]
> What do you mean? The script is waiting for the user to confirm the 2FA request, so it will not go further until you have pressed Enter

I don't use 2 Factor auth but it requested the first time also 2 Factor auth.
I had to close the programm and restart it it in order that it was able to login on mobile.

Btw. about mobile, the daily news tasks doesnt seem to work (read 10 news for 30 points).
Also 2 searches on mobile werent made and the daily login bonus weren't claimed.

**Comment by charlesbel** [comment]
Just published a fix for the missing tasks, try it

**Comment by Kurotaku-sama** [comment]
> Just published a fix for the missing tasks, try it

Now I get this error ...

[MORE PROMO] Completed More Promotions successfully !
Traceback (most recent call last):
  File "/home/pi/Programme/Microsoft-Rewards-Farmer-3.0/main.py", line 115, in <module>
    remainingSearches, remainingSearchesM = utils.getRemainingSearches()
  File "/home/pi/Programme/Microsoft-Rewards-Farmer-3.0/lib/utils.py", line 140, in getRemainingSearches
    dashboard = self.getDashboardData()
  File "/home/pi/Programme/Microsoft-Rewards-Farmer-3.0/lib/utils.py", line 89, in getDashboardData
    return self.browser.execute_script("return dashboard")
  File "/home/pi/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 406, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
  File "/home/pi/.local/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 346, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: javascript error: dashboard is not defined
  (Session info: headless chrome=113.0.5672.95)
Stacktrace:
#0 0x005579b4a088 <unknown>
#1 0x0055798b9808 <unknown>
#2 0x0055798bd60c <unknown>
#3 0x0055798bf19c <unknown>
#4 0x005579922aec <unknown>
#5 0x0055799221c4 <unknown>
#6 0x0055798e4aa8 <unknown>
#7 0x0055798e5a04 <unknown>
#8 0x005579b10aec <unknown>
#9 0x005579b136b0 <unknown>
#10 0x005579b13c88 <unknown>
#11 0x005579b1b6e4 <unknown>
#12 0x005579b142dc <unknown>
#13 0x005579aeeda0 <unknown>
#14 0x005579b32e98 <unknown>
#15 0x005579b33028 <unknown>
#16 0x005579b426c4 <unknown>
#17 0x007fb9a33648 start_thread
#18 0x007fb955ec1c <unknown>

**Comment by charlesbel** [comment]
could you run it with -v argument and show on which page you are when the error occurs

**Comment by Kurotaku-sama** [comment]
> could you run it with -v argument and show on which page you are when the error occurs

The last page I see is this one
https://rewards.bing.com/status/

**Comment by charlesbel** [comment]
> > could you run it with -v argument and show on which page you are when the error occurs
> 
> The last page I see is this one
> https://rewards.bing.com/status/

You should never be on this page, I don't understand why you are on. Could like screen record what's happening on the browser ?

**Comment by charlesbel** [comment]
> > could you run it with -v argument and show on which page you are when the error occurs
> 
> The last page I see is this one https://rewards.bing.com/status/

Fixed, try it !
