### ISSUE TITLE
stuck at logged in!

### ISSUE THREAD

**Issue by rusted-dreams** [charlesbel/Microsoft-Rewards-Farmer#192]
tried to run the script multiple times but always stuck at logged in.

**Comment by rusted-dreams** [comment]
![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/123829783/dd3f06d3-5fc9-4c08-bad7-15d05f073a1b)

**Comment by charlesbel** [comment]
Run it with -v argument to open up the browser so we can check what's this issue

**Comment by rusted-dreams** [comment]
![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/123829783/7fd7b3d9-17ba-4d9a-990b-a1a59da41470)

It's stuck in there is it related to location issues?

**Comment by charlesbel** [comment]
> ![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/123829783/7fd7b3d9-17ba-4d9a-990b-a1a59da41470)
> 
> It's stuck in there is it related to location issues?
> 

I can see that the page seems to not finish loading, and so, the bot cannot continue. Is your internet or your computer slow ? Does it fully load in a different browser ?

**Comment by rusted-dreams** [comment]
Ya it does I tried it on the same chromium browser manually without the script and it worked fine.

**Comment by Braxxa** [comment]
Same issue here!

**Comment by SunFromRu** [comment]
same issue

**Comment by SunFromRu** [comment]
you need to install microsoft reward extension for each instance

**Comment by charlesbel** [comment]
Does the page fully load in another browser without the reward extension ?

**Comment by charlesbel** [comment]
Also, it should throw a TimeoutException error after 30 or 60 sec, isn't it ?

**Comment by SunFromRu** [comment]
> Also, it should throw a TimeoutException error after 30 or 60 sec, isn't it ?
yes and all works fine when browser with extension, you as developer can make a auto download extension for broswer session/desktop/Default/Extensions

**Comment by charlesbel** [comment]
What country are you in ?

**Comment by rusted-dreams** [comment]
India

**Comment by charlesbel** [comment]
Fixed, try it !

**Comment by rusted-dreams** [comment]
Thanks man really appreciate your work ❤️.

**Comment by asian-farmer** [comment]
@charlesbel I am facing the same issue. It is stuck on logged-in, using -v it shows the same page as reported by @rusted-dreams and the page has loaded completely. There is no timeout as well. I am using the latest release zip.

**Comment by shishixiu** [comment]
Ihave the same problem. Can you add China? Thanks
