### ISSUE TITLE
[BUG] Daily Set not 100% complete (Test your smarts quiz)

### ISSUE THREAD

**Issue by Gigafrost** [charlesbel/Microsoft-Rewards-Farmer#194]
Let me just start by saying that I absolutely love this script! Keep up the great work!

I noticed that the farmer doesn't complete all of the daily set quizzes, namely the "Test your smarts" quiz.

![Screenshot_20230721-065938](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/3525107/5a878871-452d-4adc-ad47-cfbdf1790b74)

Is there any way to get it to double check if all the daily set was completed and if not, to try and complete any remaining sets? Or atleast a way to fix it so that it does all of them? Another way could be that it checks whether or not your current streak has changed after the daily set, and if it hasn't, to try to complete the missing set again. Thanks!

**Comment by charlesbel** [comment]
I wasn't aware of this type of quizz so the script does not handle it.
What's your country ?

**Comment by Gigafrost** [comment]
My country is the United States.

**Comment by charlesbel** [comment]
> My country is the United States. I think this is one of the newer quizzes. I haven't heard of it either until these past few days.

Ok thanks, I am going to add it very soon.

**Comment by Gigafrost** [comment]
No problem! Thanks for responding so quickly!

**Comment by charlesbel** [comment]
You can try my latest commit : )

**Comment by Gigafrost** [comment]
Awesome thank you!

I already did today's quizzes but will for sure check again on it tomorrow and let you know!

**Comment by Gigafrost** [comment]
Checked today and the daily set is now working beautifully! Thank you so much!
