### ISSUE TITLE
Stuck at Logged in

### ISSUE THREAD

**Issue by MaskBoyz** [charlesbel/Microsoft-Rewards-Farmer#195]
Theres no error may be its somekind of bugs or i have some problem but its seems everything run fine but after logged in its not doing anything and the page also loaded clearly.

![Screenshot (9)](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/137426181/b7c25c91-724a-4837-b5b0-65707b0099d8)

here's the screenshot of command window
![Screenshot (11)](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/137426181/fc6aacc6-56b5-4087-844c-3d285829a776)

**Comment by SunFromRu** [comment]
https://github.com/charlesbel/Microsoft-Rewards-Farmer/issues/192

**Comment by charlesbel** [comment]
What country are you in ?

**Comment by MaskBoyz** [comment]
Bangladesh and i think thats why its not working cause when i connect to vpn and usa its work fine but its kinda slow is it possible to make it faster and work from my country its will be helpful .

**Comment by charlesbel** [comment]
Fixed, try it !
