### ISSUE TITLE
Proxies support

### ISSUE THREAD

**Issue by bscongluanbui** [charlesbel/Microsoft-Rewards-Farmer#197]
Can you add proxies support?

**Comment by charlesbel** [comment]
Will try to add it

**Comment by ShoGinn** [comment]
> Would be great to have that on an account by bases so you can segregate accounts. Just another setting in the accounts.json file.

can you give me an example of how you are utilizing proxies now?

* Simple HTTPS proxy?
* Authenticated Proxy?

Per user for a simple https proxy is an easy add but the 2nd is much more difficult :)

**Comment by Lucifer1590** [comment]
> > Would be great to have that on an account by bases so you can segregate accounts. Just another setting in the accounts.json file.
> 
> can you give me an example of how you are utilizing proxies now?
> 
>     * Simple HTTPS proxy?
> 
>     * Authenticated Proxy?
> 
> 
> Per user for a simple https proxy is an easy add but the 2nd is much more difficult :)

we can start with simple https proxy then we can implement auth one 

most providers support ip whitelisting

**Comment by malesci** [comment]
> > Would be great to have that on an account by bases so you can segregate accounts. Just another setting in the accounts.json file.
> 
> can you give me an example of how you are utilizing proxies now?
> 
> * Simple HTTPS proxy?
> * Authenticated Proxy?
> 
> Per user for a simple https proxy is an easy add but the 2nd is much more difficult :)

In my view the authenticated proxy will be very helpful

**Comment by charlesbel** [comment]
Just added selenium-wire, will soon implement using it proxies !

**Comment by charlesbel** [comment]
It's now implemented, take a look at the readme for usage.
