### ISSUE TITLE
not an issue but a question

### ISSUE THREAD

**Issue by bucks9052** [charlesbel/Microsoft-Rewards-Farmer#2]
how long do you think it will take to add in a thing to auto do quizes

**Comment by charlesbel** [comment]
I am working on, that's very complex because it change each days but it should be released within the next 20 days

**Comment by charlesbel** [comment]
> how long do you think it will take to add in a thing to auto do quizes

Hi, I just published the update, it complete now quizes, daily set, punch cards... Have fun !
