### ISSUE TITLE
Stop from closing after finished

### ISSUE THREAD

**Issue by pearlheartgtr** [charlesbel/Microsoft-Rewards-Farmer#202]
Is there something I can change in the code to keep the window from closing after the bot is finished? The old version stayed open and I could see if it collected all of the points or if I had to run it again.

**Comment by charlesbel** [comment]
> Is there something I can change in the code to keep the window from closing after the bot is finished? The old version stayed open and I could see if it collected all of the points or if I had to run it again.

You can just add an input() on the bottom of main.py to avoid it to close
