### ISSUE TITLE
Stuck on "Writing Password"

### ISSUE THREAD

**Issue by Wasdniak** [charlesbel/Microsoft-Rewards-Farmer#203]
I'm sure I could just be doing something wrong, but when I run the script it gets to the "writing password" stage and doesn't progress any further. I'm on Windows 11 with the latest stable build of Chrome and ChromeDriver to match; Version 115.0.5790.

**Comment by charlesbel** [comment]
> I'm sure I could just be doing something wrong, but when I run the script it gets to the "writing password" stage and doesn't progress any further. I'm on Windows 11 with the latest stable build of Chrome and ChromeDriver to match; Version 115.0.5790.

Could you run it with -v argument so we can see what's happening in the browser

**Comment by Wasdniak** [comment]
Ah, it seemed like it was waiting for a 2factor code but wasn't saying that in powershell. Put it in with the window up and now it's all good.
