### ISSUE TITLE
[BUG] stuck on ensuring login on bing after successfully completing promotions

### ISSUE THREAD

**Issue by mgrimace** [charlesbel/Microsoft-Rewards-Farmer#205]
I'm stuck on `[LOGIN] Ensuring login on Bing...` after succesfully completing the promotions. There are no errors or timeouts, it just stalls here indefinitely:

```
[LOGIN] Logging-in...
[LOGIN] Logged-in !
[LOGIN] Ensuring login on Bing...
[LOGIN] Logged-in successfully !
[POINTS] You have 72163 points on your account !
[DAILY SET] Trying to complete the Daily Set...
[DAILY SET] Completed the Daily Set successfully !
[PUNCH CARDS] Trying to complete the Punch Cards...
[PUNCH CARDS] Completed the Punch Cards successfully !
[MORE PROMO] Trying to complete More Promotions...
[MORE PROMO] Completed More Promotions successfully !
[LOGIN] Logging-in...
[LOGIN] Writing email...
[LOGIN] Writing password...
[LOGIN] Logged-in !
[LOGIN] Ensuring login on Bing...
```

Re-running with `-v` flag and the brower is just open at bing.com with no further action. The page is not frozen, I can click around. 

**Screenshot of the page**
<img width="1195" alt="Screen Shot 2023-07-24 at 11 25 15 AM" src="https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/55518507/d525e69a-0908-4f46-86ca-a6ed4cbf1eec">

**Additional details**
I've tried this on a mac and my home ubuntu server, it seems to stall at the same point on both

**Comment by charlesbel** [comment]
Fixed !
