### ISSUE TITLE
[BUG] dashboard not deffined ... dashboardResult is

### ISSUE THREAD

**Issue by zosky** [charlesbel/Microsoft-Rewards-Farmer#206]
hiYa. its likely `return dashboard ?? dashboardResult` would sort this out, or let it `try`

```
    def getDashboardData(self) -> dict:
        try:
            return self.browser.execute_script("return dashboard")
        except: 
            return self.browser.execute_script("return dashboardResult")
```

not sure if you see comments on closed bugs or if you wanna re-open it
i need the cookieBannerHack i mentioned in #187 to get this far

thanks again

**Comment by charlesbel** [comment]
#187 has been implemented. Where did you find this "dashboardResult", I've never seen that...

**Comment by zosky** [comment]
maybe it had "the mondays" ? 

after `[MORE PROMO]` it kept dying, so i did `-v` & found it in console w/ autoComplete. 

now it looks like `dashboard` always again ?!?!

```
[MORE PROMO] Trying to complete More Promotions...
[MORE PROMO] Completed More Promotions successfully !
Traceback (most recent call last):
  File "./main.py", line 115, in <module>
    remainingSearches, remainingSearchesM = utils.getRemainingSearches()
  File "/home/zosky/Microsoft-Rewards-Farmer/lib/utils.py", line 141, in getRemainingSearches
    dashboard = self.getDashboardData()
  File "/home/zosky/Microsoft-Rewards-Farmer/lib/utils.py", line 89, in getDashboardData
    return self.browser.execute_script("return dashboard")
  File "/home/zosky/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 491, in execute_script
    return self.execute(command, {
  File "/home/zosky/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "/home/zosky/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: javascript error: dashboard is not defined
  (Session info: chrome=114.0.5735.198)
Stacktrace:
```

**Comment by zosky** [comment]
found it: `earn` page its dashboard... but notFound @ `redeem` & `status`

not sure its anything exciting. the contents look the same.

![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/112049/689f267a-8483-4931-a13f-a53158d953da)

**Comment by ShoGinn** [comment]
> found it: `earn` page its dashboard... but notFound @ `redeem` & `status`
> 
> not sure its anything exciting. the contents look the same.
> 
> ![image](https://user-images.githubusercontent.com/112049/255972527-689f267a-8483-4931-a13f-a53158d953da.png)

I think you have it backwards, i just looked and its not under `earn` but under Redeem & status.. i dont see this as an issue since the bot should never be in those tabs ;)

**Comment by charlesbel** [comment]
> > found it: `earn` page its dashboard... but notFound @ `redeem` & `status`
> > 
> > not sure its anything exciting. the contents look the same.
> > 
> > ![image](https://user-images.githubusercontent.com/112049/255972527-689f267a-8483-4931-a13f-a53158d953da.png)
> 
> I think you have it backwards, i just looked and its not under `earn` but under Redeem & status.. i dont see this as an issue since the bot should never be in those tabs ;)

I totally agree, if your bot is going to these pages feel free to open another issue so we can fix that.
