### ISSUE TITLE
[BUG] Supersonic Quiz and Daily poll not completed

### ISSUE THREAD

**Issue by Gigafrost** [charlesbel/Microsoft-Rewards-Farmer#208]
I don't know why but it looks like the supersonic quiz and daily poll didn't complete anymore

![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/3525107/f8becf7b-c453-4061-b066-be91dba5ef8c)

Any thoughts?

I am a US user by the way

**Comment by Gigafrost** [comment]
I can definitely try! How do I add the argument? Do I just run it from the command prompt?

**Comment by Gigafrost** [comment]
Update! I started the program a second time and it completed the quizzes!

**Comment by charlesbel** [comment]
Might be related to slow internet
