### ISSUE TITLE
Multi-Threaded

### ISSUE THREAD

**Issue by superfastisfast** [charlesbel/Microsoft-Rewards-Farmer#210]
use threading, or some module like that to make the program much more efficient.

**Comment by charlesbel** [comment]
it can't really be used for simultaneous tasks on the same accounts, but it can be implemented to run multiple accounts at the same time, is it what you were thinking of ?

**Comment by ShoGinn** [comment]
Running multiple selenium chromedriver instances using threading is problematic. And in the interest of keeping at least close to the MS intended use agreements I recommend not pursuing threading.

**Comment by charlesbel** [comment]
Will not be implemented, I agree with @ShoGinn
