### ISSUE TITLE
Sometimes its get pause

### ISSUE THREAD

**Issue by MaskBoyz** [charlesbel/Microsoft-Rewards-Farmer#211]
Sometimes its get paused like after ( Ensuring login on Bing...) its just stuck on the same page but when click on the cmd window and click enter its resume again I just wanna know is this intended, if not then what can I do that it wont get paused.

**Comment by charlesbel** [comment]
it is not supposed to get paused, there is no input in this part of the program...

**Comment by s0fax** [comment]
It sounds like you are clicking in the CMD window with the mouse and this activates the selection mode, so the CMD pauses so you can mark in peace and with Enter you leave this mode.

**Comment by charlesbel** [comment]
> It sounds like you are clicking in the CMD window with the mouse and this activates the selection mode, so the CMD pauses so you can mark in peace and with Enter you leave this mode.

Thanks for your comment
