### ISSUE TITLE
[BUG] Chromedriver Executable needs to be in PATH

### ISSUE THREAD

**Issue by gimmx** [charlesbel/Microsoft-Rewards-Farmer#217]
*MAKE SURE THE ERROR IS NOT FROM YOU, THIS IS THE MOST FREQUENT CASE*

**Error Log**
AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home

Selenium was updated. This can be fixed by defining "service=" in src/browser.py just before the return, e.g.:

```
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
...
s = Service(ChromeDriverManager(version="114.xxx").install())
return webdriver.Chrome(service=s, options=options)
```

**Comment by udu3324** [comment]
You need to download [chromedriver.exe](https://chromedriver.chromium.org/downloads/version-selection) and put it in C:\Windows

Like this:
![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/47045986/8683fb66-f53a-4c24-b757-e6fcc8a834d4)

**Comment by charlesbel** [comment]
> _MAKE SURE THE ERROR IS NOT FROM YOU, THIS IS THE MOST FREQUENT CASE_
> 
> **Error Log** AppData\Local\Programs\Python\Python38-32\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start raise WebDriverException( selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home
> 
> Selenium was updated. This can be fixed by defining "service=" in src/browser.py just before the return, e.g.:
> 
> ```
> from selenium.webdriver.chrome.service import Service
> from webdriver_manager.chrome import ChromeDriverManager
> ...
> s = Service(ChromeDriverManager(version="114.xxx").install())
> return webdriver.Chrome(service=s, options=options)
> ```

You're right but since selenium v4.1.0 you no longer need to have chromedriver in the PATH because Selenium Manager is included in the package. Please check you are using the latest selenium.
