### ISSUE TITLE
Auto Update 

### ISSUE THREAD

**Issue by MaskBoyz** [charlesbel/Microsoft-Rewards-Farmer#219]
hey its will be helpful to have a auto update feature whats will update the script if theres a new version or new feature added or maybe make an option to check updates if theres something new stable available then its will update the script

**Comment by charlesbel** [comment]
Please check : https://github.com/charlesbel/Microsoft-Rewards-Farmer/commit/c68b307360b8e7d0aba5e19390bc529608dcb1cd

**Comment by MaskBoyz** [comment]
thank you its working fine

**Comment by MaskBoyz** [comment]
I saw theres an exception in sessions however its remove the sessions folder or remove everything inside session folder then when i run this its login again every time account by email pass its take quite a lot of time hope its will be fix soon

**Comment by charlesbel** [comment]
> I saw theres an exception in sessions however its remove the sessions folder or remove everything inside session folder then when i run this its login again every time account by email pass its take quite a lot of time hope its will be fix soon
> 

I think I know why, I messed up something, I'll fix it very soon 😁

**Comment by MaskBoyz** [comment]
okh Brother  😁

**Comment by charlesbel** [comment]
Fixed now !

**Comment by charlesbel** [comment]
I deployed an "autoupdate_main.py", wich you can run scheduled, it will on each run check if a new version if available, download it and run it. Works same as "main.py" but will always be up to date.
