### ISSUE TITLE
Move To Gitlab

### ISSUE THREAD

**Issue by Lucifer1590** [charlesbel/Microsoft-Rewards-Farmer#220]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Describe the bug

I would recommend you to move to gitlab immediately so that we do not repeat farshadz case/ or we can make a tg group to be in touch for continuous development 

just my 2 cents 

### Copy and paste your error

xx----xx

### Screenshot of the bug

xx----xx

### Value of dashboard variable

xx----xx

**Comment by udu3324** [comment]
Duplicate of #201
