### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Jondrg** [charlesbel/Microsoft-Rewards-Farmer#221]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Describe the bug

After that error the programm crashed and it´s always the same. Is it a user issue or a script issue? 

### Copy and paste your error

Didn´t had time to copy.

### Screenshot of the bug

![Screenshot 2023-07-28 152547 - Kopie](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/70908424/0be60b4f-327a-44e2-af7a-bb952dc651d5)

### Value of dashboard variable

Is this really necessary?

**Comment by ShoGinn** [comment]
What level is your account? seems this is a german client?

I have seen other international accounts have this issue because the html is different

**Comment by Jondrg** [comment]
My account is on lvl 2

**Comment by Jondrg** [comment]
I have to comment line 58 in login.py out, because it always gets stuck at "Ensuring login on Bing...". Maybe that´s the problem?

**Comment by ShoGinn** [comment]
the problem is the `fly_id_rc` on the `bing.com` webpage that is probably formatted weird.

when you goto bing.com and click on the rewards icon it should look like this:

<img width="396" alt="image" src="https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/2660603/63d41e7b-a537-4178-a75f-03edad8c58b9">

**Comment by Jondrg** [comment]
Yea it looks like this

**Comment by ShoGinn** [comment]
@charlesbel i'll let you tackle this since it seems that there might be a flyout problem

**Comment by charlesbel** [comment]
> @charlesbel i'll let you tackle this since it seems that there might be a flyout problem

I think we will deprecate this use of fly_id_rc to solve this type of problem by replacing it by a web request

**Comment by Jondrg** [comment]
@charlesbel will you update it?

**Comment by charlesbel** [comment]
> @charlesbel will you update it? 
> 

Yes, working on it

**Comment by Jondrg** [comment]
> > @charlesbel will you update it?
> 
> Yes, working on it

Thanks!!

**Comment by charlesbel** [comment]
Just deployed a fix removing actions with id_rc and fly_id_rc
