### ISSUE TITLE
[BUG] ssl error code 1

### ISSUE THREAD

**Issue by slickochet** [charlesbel/Microsoft-Rewards-Farmer#224]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Describe the bug

Error is as in the comment.  Happens constantly but most functions do eventually finish (see screenshot).

### Copy and paste your error

error ssl_client_socket_imp_cc(980 handshake failed; return -1, ssl error code 1, net_error -202

### Screenshot of the bug

![2023-07-28 22_22_46-Greenshot](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/20989696/6515583d-8309-4751-a42f-c264e3615137)

### Value of dashboard variable

[dashboard.txt](https://github.com/charlesbel/Microsoft-Rewards-Farmer/files/12198700/dashboard.txt)

**Comment by charlesbel** [comment]
Not an important error, we don't actually care about it, the script works well even with it
