### ISSUE TITLE
[BUG] Stuck at Logged-In!

### ISSUE THREAD

**Issue by Bulwarini** [charlesbel/Microsoft-Rewards-Farmer#225]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Describe the bug

So im stuck, is this an region bug?
Im from Poland

### Copy and paste your error

[LOGIN] Logged-in !

### Screenshot of the bug

![obraz](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/81563389/c834f51d-3fa3-47b1-9705-96fd93d8f6e1)
![obraz](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/81563389/909349b1-73c1-4a5e-b581-b427faeb3cae)

### Value of dashboard variable

var dashboard = {"userStatus":{"levelInfo":{"activeLevel":"Level1","activeLevelName":"Level 1","progress":35,"progressMax":500,"levels":[{"key":"Level1","active":true,"name":"Level 1","tasks":[{"text":"Free and included with your Microsoft account","url":null}],"privileges":[{"text":"3 points per Bing Search, up to 30 points per day","url":"//www.bing.com/?FORM=MA1368"},{"text":"1 point per $1 spent in Microsoft Store, plus earn bonus points on select purchases","url":"//www.microsoftstore.com"},{"text":"Points for exploring offers from Microsoft Rewards","url":"/rewards/dashboard"},{"text":"Access to member sales and discounts","url":null},{"text":"Redeem your points for gift cards, sweepstakes entries, or donate them to charity","url":"/rewards/redeem"}]},{"key":"Level2","active":false,"name":"Level 2","tasks":[{"text":"Earn at least 500 points each month","url":null}],"privileges":[{"text":"3 points per Bing Search, up to 150 points per day","url":"//www.bing.com/?FORM=MA1368"},{"text":"Level 1 Microsoft Store benefits, plus exclusive Level 2 bonus offers","url":null},{"text":"Points for exploring offers from Microsoft Rewards","url":"/rewards/dashboard"},{"text":"Access to member sales and discounts, with exclusives for Level 2 members","url":null},{"text":"Get up to 10% off when redeeming rewards from Microsoft brands","url":null}]}],"benefitsPromotion":{"benefits":[{"key":"BingSearch","text":"Daily Bing search point limit (3 points per search)*","url":"https://www.bing.com/?FORM=MA1368","helpText":"* The Level 2 Bing search benefit is the sum of 150 points on PC and 100 points on mobile","supportedLevels":{"level1":"50","level2":"250","level2XBoxGold":"250"}},{"key":"EdgeSearch","text":"Bing search bonus daily cap for Microsoft Edge ","url":"https://www.microsoft.com/rewards/edge-bonus?form=ML18S8\u0026OCID=ML18S8\u0026rtc=1","helpText":null,"supportedLevels":{"level1":"5","level2":"20","level2XBoxGold":"20"}},{"key":"PointsDollarSpent","text":"Points earned per $ spent in Microsoft Store online**","url":"https://www.microsoft.com/store/b/home?rtc=1","helpText":"**Qualifying content only. \u003ca class=\u0027c-hyperlink\u0027 href=\u0027https://www.microsoft.com/rewards/xbox/transition-overview?form=ML18S9\u0026OCID=ML18S9\u0026rtc=1\u0027\u003eSee more\u003c/a\u003e for details.","supportedLevels":{"level1":"1:1","level2":"10:1","level2XBoxGold":"20:1"}},{"key":"PointsSeeDailyOffers","text":"Points for exploring daily offers","url":"https://account.microsoft.com/rewards","helpText":null,"supportedLevels":{"level1":"","level2":"","level2XBoxGold":""}},{"key":"MemberDiscounts","text":"Access to exclusive member sales and discounts","url":null,"helpText":null,"supportedLevels":{"level2":"","level2XBoxGold":""}},{"key":"MemberInvites","text":"Occasional surprise invites to exclusive member-only events","url":null,"helpText":null,"supportedLevels":{"level2":"","level2XBoxGold":""}},{"key":"RedeemOff","text":"Up to 10% off when redeeming from Microsoft brands","url":null,"helpText":null,"supportedLevels":{"level2":"","level2XBoxGold":""}}],"supportedLevelKeys":["level1","level2","level2XBoxGold"],"supportedLevelTitles":["Level 1","Level 2","Level 2\u003cbr/\u003e\u003cspan class=\u0027highlightGold\u0027\u003e+Xbox Live Gold\u003c/span\u003e"],"supportedLevelTitlesMobile":["Level 1","Level 2","Level 2 +Xbox Live Gold"],"activeLevel":"level1","name":"level_benefits","priority":1,"attributes":{"hidden":"True","benefits":"[{ key: \u0027BingSearch\u0027, text: \u0027Daily Bing search point limit (3 points per search)*\u0027, url: \u0027https://www.bing.com/?FORM=MA1368\u0027, helpText: \u0027* The Level 2 Bing search benefit is the sum of 150 points on PC and 100 points on mobile\u0027, supportedLevels: { \u0027level1\u0027: \u002750\u0027, \u0027level2\u0027: \u0027250\u0027, level2XBoxGold: \u0027250\u0027 } }, { key: \u0027EdgeSearch\u0027, text: \u0027Bing search bonus daily cap for Microsoft Edge \u0027, url: \u0027https://www.microsoft.com/rewards/edge-bonus?form=ML18S8\u0026OCID=ML18S8\u0026rtc=1\u0027, supportedLevels: { \u0027level1\u0027: \u00275\u0027, \u0027level2\u0027: \u002720\u0027, level2XBoxGold: \u002720\u0027 } }, { key: \u0027PointsDollarSpent\u0027, text: \u0027Points earned per $ spent in Microsoft Store online**\u0027, url: \u0027https://www.microsoft.com/store/b/home?rtc=1\u0027, helpText: \u0027**Qualifying content only. \u003ca class=\\\u0027c-hyperlink\\\u0027 href=\\\u0027https://www.microsoft.com/rewards/xbox/transition-overview?form=ML18S9\u0026OCID=ML18S9\u0026rtc=1\\\u0027\u003eSee more\u003c/a\u003e for details.\u0027, supportedLevels: { \u0027level1\u0027: \u00271:1\u0027, \u0027level2\u0027: \u002710:1\u0027, level2XBoxGold: \u002720:1\u0027 } }, { key: \u0027PointsSeeDailyOffers\u0027, text: \u0027Points for exploring daily offers\u0027, url: \u0027https://account.microsoft.com/rewards\u0027, supportedLevels: { \u0027level1\u0027: \u0027\u0027, \u0027level2\u0027: \u0027\u0027, level2XBoxGold: \u0027\u0027 } }, { key: \u0027MemberDiscounts\u0027, text: \u0027Access to exclusive member sales and discounts\u0027, supportedLevels: { \u0027level2\u0027: \u0027\u0027, level2XBoxGold: \u0027\u0027 }  }, { key: \u0027MemberInvites\u0027, text: \u0027Occasional surprise invites to exclusive member-only events\u0027, supportedLevels: { \u0027level2\u0027: \u0027\u0027, level2XBoxGold: \u0027\u0027 }}, { key: \u0027RedeemOff\u0027, text: \u0027Up to 10% off when redeeming from Microsoft brands\u0027, supportedLevels: { \u0027level2\u0027: \u0027\u0027, level2XBoxGold: \u0027\u0027 }}]","supportedLevelKeys":"level1;level2;level2XBoxGold","supportedLevelTitle":"Level 1;Level 2;Level 2\u003cbr/\u003e\u003cspan class=\u0027highlightGold\u0027\u003e+Xbox Live Gold\u003c/span\u003e","levelTitleMobile":"Level 1;Level 2;Level 2 +Xbox Live

**Comment by asian-farmer** [comment]
facing same issue from india

**Comment by omarwastaken** [comment]
> ### Before submitting a bug report...
> * [x]  This bug wasn't already reported.
>   (I have checked every bug report on GitHub)
> 
> ### Describe the bug
> So im stuck, is this an region bug? Im from Poland
> 
> ### Copy and paste your error
> [LOGIN] Logged-in !
> 
> ### Screenshot of the bug
> ![obraz](https://user-images.githubusercontent.com/81563389/256961227-c834f51d-3fa3-47b1-9705-96fd93d8f6e1.png) ![obraz](https://user-images.githubusercontent.com/81563389/256961492-909349b1-73c1-4a5e-b581-b427faeb3cae.png)
> 
> ### Value of dashboard variable
> var dashboard = {"userStatus":{"levelInfo":{"activeLevel":"Level1","activeLevelName":"Level 1","progress":35,"progressMax":500,"levels":[{"key":"Level1","active":true,"name":"Level 1","tasks":[{"text":"Free and included with your Microsoft account","url":null}],"privileges":[{"text":"3 points per Bing Search, up to 30 points per day","url":"//www.bing.com/?FORM=MA1368"},{"text":"1 point per $1 spent in Microsoft Store, plus earn bonus points on select purchases","url":"//www.microsoftstore.com"},{"text":"Points for exploring offers from Microsoft Rewards","url":"/rewards/dashboard"},{"text":"Access to member sales and discounts","url":null},{"text":"Redeem your points for gift cards, sweepstakes entries, or donate them to charity","url":"/rewards/redeem"}]},{"key":"Level2","active":false,"name":"Level 2","tasks":[{"text":"Earn at least 500 points each month","url":null}],"privileges":[{"text":"3 points per Bing Search, up to 150 points per day","url":"//www.bing.com/?FORM=MA1368"},{"text":"Level 1 Microsoft Store benefits, plus exclusive Level 2 bonus offers","url":null},{"text":"Points for exploring offers from Microsoft Rewards","url":"/rewards/dashboard"},{"text":"Access to member sales and discounts, with exclusives for Level 2 members","url":null},{"text":"Get up to 10% off when redeeming rewards from Microsoft brands","url":null}]}],"benefitsPromotion":{"benefits":[{"key":"BingSearch","text":"Daily Bing search point limit (3 points per search)_","url":"https://www.bing.com/?FORM=MA1368","helpText":"_ The Level 2 Bing search benefit is the sum of 150 points on PC and 100 points on mobile","supportedLevels":{"level1":"50","level2":"250","level2XBoxGold":"250"}},{"key":"EdgeSearch","text":"Bing search bonus daily cap for Microsoft Edge ","url":"https://www.microsoft.com/rewards/edge-bonus?form=ML18S8\u0026OCID=ML18S8\u0026rtc=1","helpText":null,"supportedLevels":{"level1":"5","level2":"20","level2XBoxGold":"20"}},{"key":"PointsDollarSpent","text":"Points earned per $ spent in Microsoft Store online**","url":"https://www.microsoft.com/store/b/home?rtc=1","helpText":"**Qualifying content only. \u003ca class=\u0027c-hyperlink\u0027 href=\u0027https://www.microsoft.com/rewards/xbox/transition-overview?form=ML18S9\u0026OCID=ML18S9\u0026rtc=1\u0027\u003eSee more\u003c/a\u003e for details.","supportedLevels":{"level1":"1:1","level2":"10:1","level2XBoxGold":"20:1"}},{"key":"PointsSeeDailyOffers","text":"Points for exploring daily offers","url":"https://account.microsoft.com/rewards","helpText":null,"supportedLevels":{"level1":"","level2":"","level2XBoxGold":""}},{"key":"MemberDiscounts","text":"Access to exclusive member sales and discounts","url":null,"helpText":null,"supportedLevels":{"level2":"","level2XBoxGold":""}},{"key":"MemberInvites","text":"Occasional surprise invites to exclusive member-only events","url":null,"helpText":null,"supportedLevels":{"level2":"","level2XBoxGold":""}},{"key":"RedeemOff","text":"Up to 10% off when redeeming from Microsoft brands","url":null,"helpText":null,"supportedLevels":{"level2":"","level2XBoxGold":""}}],"supportedLevelKeys":["level1","level2","level2XBoxGold"],"supportedLevelTitles":["Level 1","Level 2","Level 2\u003cbr/\u003e\u003cspan class=\u0027highlightGold\u0027\u003e+Xbox Live Gold\u003c/span\u003e"],"supportedLevelTitlesMobile":["Level 1","Level 2","Level 2 +Xbox Live Gold"],"activeLevel":"level1","name":"level_benefits","priority":1,"attributes":{"hidden":"True","benefits":"[{ key: \u0027BingSearch\u0027, text: \u0027Daily Bing search point limit (3 points per search)_\u0027, url: \u0027https://www.bing.com/?FORM=MA1368\u0027, helpText: \u0027_ The Level 2 Bing search benefit is the sum of 150 points on PC and 100 points on mobile\u0027, supportedLevels: { \u0027level1\u0027: \u002750\u0027, \u0027level2\u0027: \u0027250\u0027, level2XBoxGold: \u0027250\u0027 } }, { key: \u0027EdgeSearch\u0027, text: \u0027Bing search bonus daily cap for Microsoft Edge \u0027, url: \u0027https://www.microsoft.com/rewards/edge-bonus?form=ML18S8\u0026OCID=ML18S8\u0026rtc=1\u0027, supportedLevels: { \u0027level1\u0027: \u00275\u0027, \u0027level2\u0027: \u002720\u0027, level2XBoxGold: \u002720\u0027 } }, { key: \u0027PointsDollarSpent\u0027, text: \u0027Points earned per $ spent in Microsoft Store online**\u0027, url: \u0027https://www.microsoft.com/store/b/home?rtc=1\u0027, helpText: \u0027**Qualifying content only. \u003ca class=\\u0027c-hyperlink\\u0027 href=\\u0027https://www.microsoft.com/rewards/xbox/transition-overview?form=ML18S9\u0026OCID=ML18S9\u0026rtc=1\\u0027\u003eSee more\u003c/a\u003e for details.\u0027, supportedLevels: { \u0027level1\u0027: \u00271:1\u0027, \u0027level2\u0027: \u002710:1\u0027, level2XBoxGold: \u002720:1\u0027 } }, { key: \u0027PointsSeeDailyOffers\u0027, text: \u0027Points for exploring daily offers\u0027, url: \u0027https://account.microsoft.com/rewards\u0027, supportedLevels: { \u0027level1\u0027: \u0027\u0027, \u0027level2\u0027: \u0027\u0027, level2XBoxGold: \u0027\u0027 } }, { key: \u0027MemberDiscounts\u0027, text: \u0027Access to exclusive member sales and discounts\u0027, supportedLevels: { \u0027level2\u0027: \u0027\u0027, level2XBoxGold: \u0027\u0027 } }, { key: \u0027MemberInvites\u0027, text: \u0027Occasional surprise invites to exclusive member-only events\u0027, supportedLevels: { \u0027level2\u0027: \u0027\u0027, level2XBoxGold: \u0027\u0027 }}, { key: \u0027RedeemOff\u0027, text: \u0027Up to 10% off when redeeming from Microsoft brands\u0027, supportedLevels: { \u0027level2\u0027: \u0027\u0027, level2XBoxGold: \u0027\u0027 }}]","supportedLevelKeys":"level1;level2;level2XBoxGold","supportedLevelTitle":"Level 1;Level 2;Level 2\u003cbr/\u003e\u003cspan class=\u0027highlightGold\u0027\u003e+Xbox Live Gold\u003c/span\u003e","levelTitleMobile":"Level 1;Level 2;Level 2 +Xbox Live

+1

**Comment by Kwadroo** [comment]
Same here in Denmark

**Comment by CaioFBC** [comment]
Same in Brazil, I guess it's a error caused by Chrome version 115.0.5790.110, since it doesn't have a WebDriver for this version, https://googlechromelabs.github.io/chrome-for-testing/.

**Comment by ecsstasyyy** [comment]
same here

**Comment by charlesbel** [comment]
Already made the fix last week but somehow it has been overriden by a PR, so put it back in, working now !
