### ISSUE TITLE
Selenium Manager [BUG]

### ISSUE THREAD

**Issue by Giosephww** [charlesbel/Microsoft-Rewards-Farmer#227]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Describe the bug

I updated the Selenium Version to the 4.10 and downloaded also the last version of the files, but since then I have this error:

### Copy and paste your error

Traceback (most recent call last):
  File "C:\Users\****\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\common\driver_finder.py", line 42, in get_path
    path = SeleniumManager().driver_location(options) if path is None else path
  File "C:\Users\****\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\common\selenium_manager.py", line 96, in driver_location
    result = self.run(args)
  File "C:\Users\****\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\common\selenium_manager.py", line 121, in run
    raise WebDriverException(f"Unsuccessful command executed: {command}.\n{result}{stderr}")
selenium.common.exceptions.WebDriverException: Message: Unsuccessful command executed: C:\Users\****\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\common\windows\selenium-manager.exe --browser chrome --output json.
Wrong browser/driver version

### Screenshot of the bug

----

### Value of dashboard variable

----

**Comment by ShoGinn** [comment]
I don't see a bug caused by any code outside of Selenium.

Highly recommend you use a virtual environment and try again.

Or you can delete the `session` folder and see if thats contributing.

I use this code base on 4.10 with no issues

**Comment by Nyegnav** [comment]
Similar error ending in;

    raise NoSuchDriverException(msg) from err
selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

**Comment by charlesbel** [comment]
> Similar error ending in;
> 
>     raise NoSuchDriverException(msg) from err
> selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain driver for chrome using Selenium Manager.; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location

Try updating chrome and selenium to the latest and everything should work

**Comment by Nyegnav** [comment]
> 

Selenium is 4.11, tried reverting to 4.10 and still didn't work.
