### ISSUE TITLE
[BUG] NFA2 code part isn't working. 

### ISSUE THREAD

**Issue by gekkefries21** [charlesbel/Microsoft-Rewards-Farmer#229]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Describe the bug

it says enter when confirmed but its a code you need to enter. I already tried to enter the code and then press enter but it just did nothing like it just goes to the next line inside the console but does nothing I waited for some minutes but does nothing. 

### Copy and paste your error

it says enter when confirmed but its a code you need to enter. I already tried to enter the code and then press enter but it just did nothing like it just goes to the next line inside the console but does nothing I waited for some minutes but does nothing. 

### Screenshot of the bug

![t87qhsi5](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/106188613/77e1a320-fd1a-4f33-a616-867cd0d2317f)

it isn't a picture of the bug btw. It was required so I just entered a random image

### Value of dashboard variable

eh

**Comment by CaioFBC** [comment]
You can use the argument -v to open a Chrome window, insert your 2FA and check "never ask again for this machine"

**Comment by charlesbel** [comment]
> ### Before submitting a bug report...
> 
> - [X] This bug wasn't already reported.
> (I have checked every bug report on GitHub)
> 
> 
> ### Describe the bug
> 
> it says enter when confirmed but its a code you need to enter. I already tried to enter the code and then press enter but it just did nothing like it just goes to the next line inside the console but does nothing I waited for some minutes but does nothing. 
> 
> 
> 
> ### Copy and paste your error
> 
> it says enter when confirmed but its a code you need to enter. I already tried to enter the code and then press enter but it just did nothing like it just goes to the next line inside the console but does nothing I waited for some minutes but does nothing. 
> 
> 
> ### Screenshot of the bug
> 
> ![t87qhsi5](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/106188613/77e1a320-fd1a-4f33-a616-867cd0d2317f)
> 
> it isn't a picture of the bug btw. It was required so I just entered a random image
> 
> ### Value of dashboard variable
> 
> eh 

What type of 2fa is it ? I can try to handle it in the program...

**Comment by gekkefries21** [comment]
Its the 6 number code. 
where it sends the code to the email and then you need to copy and paste it so you can verify.

**Comment by gekkefries21** [comment]
> You can use the argument -v to open a Chrome window, insert your 2FA and check "never ask again for this machine"

Eh I will try

**Comment by charlesbel** [comment]
Considering it as resolved when using -v arg
