### ISSUE TITLE
Not Completing Warpspeed Quiz

### ISSUE THREAD

**Issue by MaskBoyz** [charlesbel/Microsoft-Rewards-Farmer#237]
This is like old Warpspeed Quiz  but instead of 4 answers its have 3 Answers and its didn't and complete like 1-2 days ago and not completing today.
The script dont stop its just skip the quiz and move on to the next one task
 

Country : US

Screenshot of the Quiz
![Screenshot (20)](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/137426181/79ae97bc-1dd8-419d-9454-a5dd2588f098)

**Comment by charlesbel** [comment]
> This is like old Warpspeed Quiz  but instead of 4 answers its have 3 Answers and its didn't and complete like 1-2 days ago and not completing today.
> The script dont stop its just skip the quiz and move on to the next one task
>  
> 
> Country : US
> 
> Screenshot of the Quiz
> ![Screenshot (20)](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/137426181/79ae97bc-1dd8-419d-9454-a5dd2588f098)
> 

Yes, the script is not handling quiz with 3 answers (apart from ABC quiz), only 2, 4 or 8 answers. I'll take a look and add it in the code.

**Comment by MaskBoyz** [comment]
okh 😘😘😘 and thanks a lot 💜

**Comment by MaskBoyz** [comment]
bro its kinda crazy but for solution there need to add just (,3) this and its work 🤣🤣🤣

**Comment by charlesbel** [comment]
Merged your PR !
