### ISSUE TITLE
[BUG] Stuck at Login

### ISSUE THREAD

**Issue by omarwastaken** [charlesbel/Microsoft-Rewards-Farmer#243]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Describe the bug

Stuck forever on logging in or writing password.

### Copy and paste your error

[LOGIN] Logging-in...
[LOGIN] Writing email...
[LOGIN] Writing password...

### Screenshot of the bug

![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/134396211/73b86add-4189-4a60-874a-d525750cd6ec)

### Value of dashboard variable

Uploaded to paste since it was too long, GitHub limited it.

https://paste.ee/p/fNSWG

**Comment by udu3324** [comment]
This happened to me too. What I did was login into the stuck account on browser to clear the 2fa, and then let the bot run again

**Comment by omarwastaken** [comment]
> This happened to me too. What I did was login into the stuck account on browser to clear the 2fa, and then let the bot run again

Didnt do anything in my case, still stuck :(

**Comment by charlesbel** [comment]
Could you please run it with -v argument and screenshot what's happening

**Comment by charlesbel** [comment]
Closing, you're welcome to reopen
