### ISSUE TITLE
Stuck at this step [LOGIN] Ensuring login on Bing...

### ISSUE THREAD

**Issue by bjbjshao** [charlesbel/Microsoft-Rewards-Farmer#244]
DevTools listening on ws://127.0.0.1:4626/devtools/browser/e98b498e-9c1d-491c-9041-9ecf18198e3a
[LOGIN] Logging-in...
[LOGIN] Logged-in !
[LOGIN] Ensuring login on Bing...

**Comment by dawnlau** [comment]
same here!

**Comment by charlesbel** [comment]
Run it with -v argument and take a screenshot of what's happening in the browser

**Comment by Zoey-uwu** [comment]
Seems like the same problem i had, ran it with -v and it gave me a similar result to the attached image (not mine cause i didn't screenshot it, but really similar if not for the codes)
I personally fixed it by deleting the cookies for the account running and then restarting, but it seems to be a temporary fix
![Immagine](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/141880128/2da3918f-d40f-4d36-9838-29ed313d1911)

**Comment by bjbjshao** [comment]
> Run it with -v argument and take a screenshot of what's happening in the browser

"Resolved after using VPN."
