### ISSUE TITLE
password sometimes crashes the program

### ISSUE THREAD

**Issue by fabiovieitas** [charlesbel/Microsoft-Rewards-Farmer#247]
Goodnight. The password sometimes crashes the program....

What happens?

![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/73303693/03da1728-0585-4268-850a-23f75cdc7921)

Google Translate

**Comment by charlesbel** [comment]
May you try to record what's happening ? Because on your screenshot I don't see the line "writing password"... Do you have a slow internet connection?

**Comment by fabiovieitas** [comment]
Good afternoon. My connection is 600mb. Great! What happens is that sometimes (not always), it hangs in that part of the image. I don't know how to describe what happens...

I notice that this occurs when asking for 2FA.

Google Translate

**Comment by charlesbel** [comment]
> Good afternoon. My connection is 600mb. Great! What happens is that sometimes (not always), it hangs in that part of the image. I don't know how to describe what happens...
> 
> I notice that this occurs when asking for 2FA.
> 
> Google Translate

Could please screen record it ? I don't really understand what's happening... Do you have to write a password after completing 2fa ?

**Comment by charlesbel** [comment]
Closing, you're welcome to reopen
