### ISSUE TITLE
[BUG] Daily Set not 100% complete (Turbocharge quiz) 

### ISSUE THREAD

**Issue by Gigafrost** [charlesbel/Microsoft-Rewards-Farmer#249]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Describe the bug

I noticed that the farmer doesn't complete all of the daily set quizzes, namely the "Turbocharge" quiz. Even though it says there are no more quizzes to complete in the daily set:

![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/3525107/f93f431b-4d07-4216-a511-dba3354066e6)

I ran it multiple times and it gave the same result, but still leaves out the turbocharge quiz:

![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/3525107/76857eb5-9476-4b60-90b0-91bac9e8a581)

### Copy and paste your error

No error, it just says its successfully completed all the quizzes.

### Screenshot of the bug

![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/3525107/f93f431b-4d07-4216-a511-dba3354066e6)

### Value of dashboard variable

![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/3525107/76857eb5-9476-4b60-90b0-91bac9e8a581)

**Comment by charlesbel** [comment]
Could you please screenshots what's happening during the execution (run it with -v argument to show the browser)

**Comment by charlesbel** [comment]
Currently can't do anything, if this happens again please take screenshots in the browser so we can see what's happening
