### ISSUE TITLE
Desktop and Mobile searches aren't being applied to my account.

### ISSUE THREAD

**Issue by Avodey** [charlesbel/Microsoft-Rewards-Farmer#251]
Hello, it's either because I've done something wrong or that this program I believe runs through Chrome. Is there any way to run it through Microsoft Edge and have it do level 2? Thank you!
![Screenshot 2023-08-11 142143](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/130594121/dde3912a-2782-4756-a50a-88574e800721)

**Comment by charlesbel** [comment]
Just run again the bot, I guess you jumped from level 1 to 2 during the last execution
