### ISSUE TITLE
[BUG] Title its not working for me 

### ISSUE THREAD

**Issue by antiprogoat** [charlesbel/Microsoft-Rewards-Farmer#255]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Describe the bug

i did all the steps but its stuck on the last step , i ll attach the screenshot.

### Copy and paste your error

[LOGIN] Logging-in...
[LOGIN] Writing email...
[LOGIN] 2FA required !
[LOGIN] Press enter when confirmed...

### Screenshot of the bug

![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/142065385/c2ae90be-de23-4cf5-a6dc-375f8c08028c)

### Value of dashboard variable

idk

**Comment by charlesbel** [comment]
Did you pressed enter as the program requests ? Did you approve the 2fa request ?
If yes for both, try doing it again but by running the program with -v argument to show up the browser (so you can see what's happening)

**Comment by antiprogoat** [comment]
1-I did press enter but it stuck there always.
2- No bcs idk how to approve 2fa. I didn't get any mails to approve 2fa

**Comment by charlesbel** [comment]
> 1-I did press enter but it stuck there always. 2- No bcs idk how to approve 2fa. I didn't get any mails to approve 2fa

"If yes for both, try doing it again but by running the program with -v argument to show up the browser (so you can see what's happening)"

**Comment by antiprogoat** [comment]
can u tell how to approve 2fa, when im not getting any mails or anything?

**Comment by charlesbel** [comment]
Open up the browser so we can see what is it asking for...

**Comment by ohioohio** [comment]
Charles I don't get how to fix this
