### ISSUE TITLE
Searches

### ISSUE THREAD

**Issue by WhiskeyDent** [charlesbel/Microsoft-Rewards-Farmer#26]
My bing searches are taking a very long time between searches, up to 15 minutes in-between searches in some cases. I get you don't want them machine gunned, but this seems excessive.

**Comment by charlesbel** [comment]
Each search take 20 seconds max, it is a time that avoid to be ban. Also, bing is very slow to show available points on an account.
I will test with a bit less time, I keep you up to date.

**Comment by charlesbel** [comment]
I tested, for slow internet connection and slow computers, these delays are pretty good. I don't think we have to change them.
