### ISSUE TITLE
[BUG] I dont know what this is called but help me

### ISSUE THREAD

**Issue by usingthisforreasons** [charlesbel/Microsoft-Rewards-Farmer#265]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Describe the bug

it keeps doing this everytime it says "logging in"

### Copy and paste your error

Backtrace:
	GetHandleVerifier [0x0048A813+48355]
	(No symbol) [0x0041C4B1]
	(No symbol) [0x00325358]
	(No symbol) [0x00321B33]
	(No symbol) [0x00318CA5]
	(No symbol) [0x00319D0A]
	(No symbol) [0x00319003]
	(No symbol) [0x00318355]
	(No symbol) [0x003182EC]
	(No symbol) [0x00316F26]
	(No symbol) [0x00317688]
	(No symbol) [0x00326B52]
	(No symbol) [0x0037CF01]
	(No symbol) [0x0036A73C]
	(No symbol) [0x0037C922]
	(No symbol) [0x0036A536]
	(No symbol) [0x003482DC]
	(No symbol) [0x003493DD]
	GetHandleVerifier [0x006EAABD+2539405]
	GetHandleVerifier [0x0072A78F+2800735]
	GetHandleVerifier [0x0072456C+2775612]
	GetHandleVerifier [0x005151E0+616112]
	(No symbol) [0x00425F8C]
	(No symbol) [0x00422328]
	(No symbol) [0x0042240B]
	(No symbol) [0x00414FF7]
	BaseThreadInitThunk [0x77517D59+25]
	RtlInitializeExceptionChain [0x77BAB79B+107]
	RtlClearBits [0x77BAB71F+191]

### Screenshots

.

### Value of dashboard variable

.

**Comment by charlesbel** [comment]
Please share the full error log

**Comment by usingthisforreasons** [comment]
![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/142119261/6ec34de3-4cd5-4b91-8f0f-ee320df7ab38)

**Comment by usingthisforreasons** [comment]
Traceback (most recent call last):
  File "C:\Users\tbonn\OneDrive\Desktop\Microsoft-Rewards-Farmer-master (1)\Microsoft-Rewards-Farmer-master\main.py", line 21, in main
    executeBot(currentAccount)
  File "C:\Users\tbonn\OneDrive\Desktop\Microsoft-Rewards-Farmer-master (1)\Microsoft-Rewards-Farmer-master\main.py", line 111, in executeBot
    accountPointsCounter = Login(desktopBrowser).login()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tbonn\OneDrive\Desktop\Microsoft-Rewards-Farmer-master (1)\Microsoft-Rewards-Farmer-master\src\login.py", line 19, in login
    self.webdriver.get("https://login.live.com/")
  File "C:\Users\tbonn\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 629, in get_wrapped
    return orig_get(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tbonn\AppData\Local\Programs\Python\Python311\Lib\site-packages\undetected_chromedriver\__init__.py", line 665, in get
    return super().get(url)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\tbonn\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 354, in get
    self.execute(Command.GET, {"url": url})
  File "C:\Users\tbonn\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 345, in execute
    self.error_handler.check_response(response)
  File "C:\Users\tbonn\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_TUNNEL_CONNECTION_FAILED
  (Session info: chrome=115.0.5790.171)
Stacktrace:
Backtrace:
        GetHandleVerifier [0x005EA813+48355]
        (No symbol) [0x0057C4B1]
        (No symbol) [0x00485358]
        (No symbol) [0x00481B33]
        (No symbol) [0x00478CA5]
        (No symbol) [0x00479D0A]
        (No symbol) [0x00479003]
        (No symbol) [0x00478355]
        (No symbol) [0x004782EC]
        (No symbol) [0x00476F26]
        (No symbol) [0x00477688]
        (No symbol) [0x00486B52]
        (No symbol) [0x004DCF01]
        (No symbol) [0x004CA73C]
        (No symbol) [0x004DC922]
        (No symbol) [0x004CA536]
        (No symbol) [0x004A82DC]
        (No symbol) [0x004A93DD]
        GetHandleVerifier [0x0084AABD+2539405]
        GetHandleVerifier [0x0088A78F+2800735]
        GetHandleVerifier [0x0088456C+2775612]
        GetHandleVerifier [0x006751E0+616112]
        (No symbol) [0x00585F8C]
        (No symbol) [0x00582328]
        (No symbol) [0x0058240B]
        (No symbol) [0x00574FF7]
        BaseThreadInitThunk [0x77517D59+25]
        RtlInitializeExceptionChain [0x77BAB79B+107]
        RtlClearBits [0x77BAB71F+191]

**Comment by charlesbel** [comment]
Did you use a proxy ?

**Comment by usingthisforreasons** [comment]
Yeah

**Comment by charlesbel** [comment]
This means your proxy is either misconfigured or down. Please check it.
