### ISSUE TITLE
[BUG]  WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1 from chrome not reachable

### ISSUE THREAD

**Issue by Yash1907** [charlesbel/Microsoft-Rewards-Farmer#266]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Describe the bug

Only happens for certain accounts. The chrome window does not open and the program moves on to the next account.

### Copy and paste your error

![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/50154127/bb951699-f39c-4dd7-bd21-406a659c1554)

### Screenshots

chrome does not open

### Value of dashboard variable

chrome does not open

**Comment by Mariobob** [comment]
Deleting the sessions folder seems to work for me
