### ISSUE TITLE
[BUG] Timed out receiving message from renderer: 300.000

### ISSUE THREAD

**Issue by e9169** [charlesbel/Microsoft-Rewards-Farmer#267]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Describe the bug

Since the last pull requests (I tried two days ago and it worked perfectly), I keep getting these errors on EVERY run...

`Timed out receiving message from renderer: 300.000
`
Sometimes it's after 2 desktop edge bing searches, sometimes after 5.... totally random.

### Copy and paste your error

2023-08-13 17:20:25,818 [ERROR] TimeoutException: Message: timeout: Timed out receiving message from renderer: 300.000
  (Session info: chrome=115.0.5790.170)
Stacktrace:
0   undetected_chromedriver             0x000000010785c6b8 undetected_chromedriver + 4937400
1   undetected_chromedriver             0x0000000107853b73 undetected_chromedriver + 4901747
2   undetected_chromedriver             0x0000000107411616 undetected_chromedriver + 435734
3   undetected_chromedriver             0x00000001073f8ac9 undetected_chromedriver + 334537
4   undetected_chromedriver             0x00000001073f873c undetected_chromedriver + 333628
5   undetected_chromedriver             0x00000001073f6faa undetected_chromedriver + 327594
6   undetected_chromedriver             0x00000001073f74fc undetected_chromedriver + 328956
7   undetected_chromedriver             0x0000000107406b68 undetected_chromedriver + 392040
8   undetected_chromedriver             0x0000000107408612 undetected_chromedriver + 398866
9   undetected_chromedriver             0x000000010741d784 undetected_chromedriver + 485252
10  undetected_chromedriver             0x00000001074237db undetected_chromedriver + 509915
11  undetected_chromedriver             0x00000001073f7a42 undetected_chromedriver + 330306
12  undetected_chromedriver             0x000000010741d5d7 undetected_chromedriver + 484823
13  undetected_chromedriver             0x00000001074940bc undetected_chromedriver + 970940
14  undetected_chromedriver             0x0000000107478de3 undetected_chromedriver + 859619
15  undetected_chromedriver             0x0000000107446d7f undetected_chromedriver + 654719
16  undetected_chromedriver             0x00000001074480de undetected_chromedriver + 659678
17  undetected_chromedriver             0x00000001078182ad undetected_chromedriver + 4657837
18  undetected_chromedriver             0x000000010781d130 undetected_chromedriver + 4677936
19  undetected_chromedriver             0x0000000107823def undetected_chromedriver + 4705775
20  undetected_chromedriver             0x000000010781e05a undetected_chromedriver + 4681818
21  undetected_chromedriver             0x00000001077f092c undetected_chromedriver + 4495660
22  undetected_chromedriver             0x000000010783b838 undetected_chromedriver + 4802616
23  undetected_chromedriver             0x000000010783b9b7 undetected_chromedriver + 4802999
24  undetected_chromedriver             0x000000010784c99f undetected_chromedriver + 4872607
25  libsystem_pthread.dylib             0x00007ff8141ca1d3 _pthread_start + 125
26  libsystem_pthread.dylib             0x00007ff8141c5bd3 thread_start + 15

Also:

2023-08-13 17:35:19,729 [ERROR] WebDriverException: Message: disconnected: not connected to DevTools
  (failed to check if window was closed: disconnected: not connected to DevTools)
  (Session info: chrome=115.0.5790.170)
Stacktrace:
0   undetected_chromedriver             0x000000010dd206b8 undetected_chromedriver + 4937400
1   undetected_chromedriver             0x000000010dd17b73 undetected_chromedriver + 4901747
2   undetected_chromedriver             0x000000010d8d5616 undetected_chromedriver + 435734
3   undetected_chromedriver             0x000000010d8bbbc1 undetected_chromedriver + 330689
4   undetected_chromedriver             0x000000010d8bb923 undetected_chromedriver + 330019
5   undetected_chromedriver             0x000000010d8d7262 undetected_chromedriver + 442978
6   undetected_chromedriver             0x000000010d95756e undetected_chromedriver + 968046
7   undetected_chromedriver             0x000000010d93cde3 undetected_chromedriver + 859619
8   undetected_chromedriver             0x000000010d90ad7f undetected_chromedriver + 654719
9   undetected_chromedriver             0x000000010d90c0de undetected_chromedriver + 659678
10  undetected_chromedriver             0x000000010dcdc2ad undetected_chromedriver + 4657837
11  undetected_chromedriver             0x000000010dce1130 undetected_chromedriver + 4677936
12  undetected_chromedriver             0x000000010dce7def undetected_chromedriver + 4705775
13  undetected_chromedriver             0x000000010dce205a undetected_chromedriver + 4681818
14  undetected_chromedriver             0x000000010dcb492c undetected_chromedriver + 4495660
15  undetected_chromedriver             0x000000010dcff838 undetected_chromedriver + 4802616
16  undetected_chromedriver             0x000000010dcff9b7 undetected_chromedriver + 4802999
17  undetected_chromedriver             0x000000010dd1099f undetected_chromedriver + 4872607
18  libsystem_pthread.dylib             0x00007ff8141ca1d3 _pthread_start + 125
19  libsystem_pthread.dylib             0x00007ff8141c5bd3 thread_start + 15

### Screenshots

The browser window closes after some time of not getting response from a (random?) search on bing

### Value of dashboard variable

https://gist.github.com/e9169/18af796916075eb5e2b7c1a3ea8a9469

**Comment by charlesbel** [comment]
Do you use a proxy ? because this looks like to be a problem either from microsoft or your internet connection, otherwise I can try to add some retry policies

**Comment by xBounceIT** [comment]
Can confirm this issue occurs also on my side at the 59/60 of the mobile searches. I have a gigabit fiber connection so it shouldn't be a problem.

For now i have set a crontab to execute the script three times a day, will see if it can be a workaround.

**Comment by charlesbel** [comment]
This means Bing is experiencing high traffic haha. I'll try to add a retry policy to avoid these timeout errors

**Comment by charlesbel** [comment]
Done with commit [6875d40](https://github.com/charlesbel/Microsoft-Rewards-Farmer/commit/6875d40750e703bfb5a548a82f90f151ede963ad)

**Comment by e9169** [comment]
> Do you use a proxy ? because this looks like to be a problem either from microsoft or your internet connection, otherwise I can try to add some retry policies

Nope, I use nothing here, no proxies, no vpn, nothing. Thanks!

**Comment by yuuyuu0514** [comment]
Hey, thanks for publishing this code. I have been using this code since early August, and had had the same problem as e9169 reported. After the developer charlesbel altered the code, I still have tons of error messages saying: "[ERROR] [BING] Timeout, retrying in 5 seconds...[0m" It seems the probability of success is totally random; sometimes there was no error from 1/34 to 34/34, and others had such continuous errors that the process didn't finish.
When such an error occurs, I stop the program but when we interrupt the program working, Chrome will continue working background, causing high CPU and memory usage. To prevent this, I have to kill the Chrome tasks manually.
Any resolution is greeted. Thank you.
(This is my first post to Github, so I might mistake the way of posting)

Retrying message example:
![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/142218426/5efee167-be70-42ff-9f13-d7bbe144e605)
