### ISSUE TITLE
This new version does not run at all.

### ISSUE THREAD

**Issue by fabiovieitas** [charlesbel/Microsoft-Rewards-Farmer#270]
Good afternoon. This new version does not run at all. Always giving error. I had to continue on the previous version....

![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/73303693/009829dc-1b80-4616-9559-7e3f3353ccab)

**Comment by Lectoid** [comment]
I had this two, so just ran the setup steps again and I got further, but then got another error

**Comment by fabiovieitas** [comment]
> Sim, você precisa instalar os requisitos

I already reinstalled. However, it still has the same error...
