### ISSUE TITLE
[Feature Request] Sending live CLI messages to webhook

### ISSUE THREAD

**Issue by Chappie18** [charlesbel/Microsoft-Rewards-Farmer#273]
It would be convenient if the bot transmitted all messages entered into the terminal to the webhook (Discord or Telegram).

**Comment by charlesbel** [comment]
Wouldn't it be a bit noisy ? Maybe be could add an argument to set a full or partial logging, what do you think ?

**Comment by udu3324** [comment]
I can go ahead and add some sort of flag like -whverbose

**Comment by Chappie18** [comment]
> Wouldn't it be a bit noisy ? Maybe be could add an argument to set a full or partial logging, what do you think ?

Normally, when I'm farming, I turn off my monitor, so being able to receive notifications for accomplished tasks will be incredibly helpful.

**Comment by charlesbel** [comment]
I'll review the PR very soon so I close this
