### ISSUE TITLE
[BUG] Start from clean environment fails unless /logs/activity.log file is being created before

### ISSUE THREAD

**Issue by malesci** [charlesbel/Microsoft-Rewards-Farmer#279]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

Start from clean environment fails unless /logs/activity.log file is being created before.

### Copy and paste your error

Traceback (most recent call last):
  File "/home/main.py", line 145, in <module>
    main()
  File "/home/main.py", line 17, in main
    setupLogging()
  File "/home/main.py", line 37, in setupLogging
    handlers.TimedRotatingFileHandler(
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/logging/handlers.py", line 214, in __init__
    BaseRotatingHandler.__init__(self, filename, 'a', encoding=encoding,
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/logging/handlers.py", line 58, in __init__
    logging.FileHandler.__init__(self, filename, mode=mode,
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/logging/__init__.py", line 1169, in __init__
    StreamHandler.__init__(self, self._open())
  File "/opt/hostedtoolcache/Python/3.10.12/x64/lib/python3.10/logging/__init__.py", line 1201, in _open
    return open_func(self.baseFilename, self.mode,
FileNotFoundError: [Errno 2] No such file or directory: '/home/logs/activity.log'
Error: Process completed with exit code 1.

### Screenshots

sorry I don't have screenshot

### Value of dashboard variable

sorry I don't have dashboard value

**Comment by charlesbel** [comment]
Does the folder "logs" is created automatically ?

**Comment by malesci** [comment]
> Does the folder "logs" is created automatically ?

Not in my case, in fact I created log folder and empty file before, and then script go

**Comment by charlesbel** [comment]
> > Does the folder "logs" is created automatically ?
> 
> Not in my case, in fact I created log folder and empty file before, and then script go

I think you should review your file writing permissions/rules because you are the only one to report such an issue...

**Comment by dayumsista** [comment]
![image](https://github.com/user-attachments/assets/2226e580-dcf7-4398-869f-41d7ab44a349)
Thiss error  happen again XD

**Comment by dayumsista** [comment]
but yea, just create folder and file by ur self and it work again 
![image](https://github.com/user-attachments/assets/495844e0-f19b-4ff1-902e-c4b0f3feb701)
