### ISSUE TITLE
[BUG] Chrome driver too new?

### ISSUE THREAD

**Issue by Lectoid** [charlesbel/Microsoft-Rewards-Farmer#283]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:50134
from session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 116.0.5845.96

I've deleted everything and started over, getting the same error. Ran pip install -r requirements.txt --upgrade and the selenum upgrade command too.

### Copy and paste your error

selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:50134
from session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 116.0.5845.96

### Screenshots

n/a

### Value of dashboard variable

n/a

**Comment by Happygamer1450** [comment]
Yep I have the same issue and I think the probable fix is downgrading chrome to 114, but that seems pretty hard to keep it on that version so we gotta wait till chromedriver updates to 116

**Comment by Chappie18** [comment]
You can temporarily download Chromium 114 and add its location to your browser.py

**Comment by charlesbel** [comment]
The temprorary fix is to uninstall undetected_chromedriver then reinstall the branch with the fix : 
```pip install -e git+https://github.com/jdholtz/undetected-chromedriver.git@f91b7d86bc257d4cb9bfc848266e82509868e2c6#egg=undetected_chromedriver```
Hope it will be merged in the main branch soon.

**Comment by kkrusher** [comment]
This version have bugs (f91b7d86bc257d4cb9bfc848266e82509868e2c6)
We should use 
`pip install -e 'git+https://github.com/jdholtz/undetected-chromedriver.git@29551bd27954dacaf09864cf77935524db642c1b#egg=undetected_chromedriver'`
and delete "sessions" folder before running.

**Comment by Chappie18** [comment]
> pip install -e 'git+https://github.com/jdholtz/undetected-chromedriver.git@29551bd27954dacaf09864cf77935524db642c1b#egg=undetected_chromedriver'

![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/67442659/5756bfef-8e39-4bcd-9cf5-72bdfc08007c)


Am i missing something?

**Comment by asian-farmer** [comment]
facing this issue and the fix mentioned throws the error as commented by @Chappie18

**Comment by e9169** [comment]
Not working for me either. Shouldn't this be re-opened or something?
