### ISSUE TITLE
[BUG] 2023-08-16 21:02:57,141 [ERROR] KeyError: 'username'←[0m

### ISSUE THREAD

**Issue by SafwanWilson** [charlesbel/Microsoft-Rewards-Farmer#284]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

Hello i get this problem 
```
New version available !
Removing old files...
Downloading...
Extracting...
Done !
Starting...
←[38;5;39m2023-08-16 21:02:57,168 [INFO] ****************************************←[0m
←[38;5;196m2023-08-16 21:02:57,169 [ERROR] KeyError: 'username'←[0m
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Microsoft-Rewards-Farmer-master\main.py", line 24, in main
    executeBot(currentAccount, notifier, args)
  File "C:\Users\Administrator\Desktop\Microsoft-Rewards-Farmer-master\main.py", line 127, in executeBot
    with Browser(mobile=False, account=currentAccount, args=args) as desktopBrowser:
  File "C:\Users\Administrator\Desktop\Microsoft-Rewards-Farmer-master\src\browser.py", line 23, in __init__
    self.username = account["username"]
KeyError: 'username'
```

### Copy and paste your error

Hello i get this problem 
```
New version available !
Removing old files...
Downloading...
Extracting...
Done !
Starting...
←[38;5;39m2023-08-16 21:02:57,168 [INFO] ****************************************←[0m
←[38;5;196m2023-08-16 21:02:57,169 [ERROR] KeyError: 'username'←[0m
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Microsoft-Rewards-Farmer-master\main.py", line 24, in main
    executeBot(currentAccount, notifier, args)
  File "C:\Users\Administrator\Desktop\Microsoft-Rewards-Farmer-master\main.py", line 127, in executeBot
    with Browser(mobile=False, account=currentAccount, args=args) as desktopBrowser:
  File "C:\Users\Administrator\Desktop\Microsoft-Rewards-Farmer-master\src\browser.py", line 23, in __init__
    self.username = account["username"]
KeyError: 'username'
```

### Screenshots

![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/89034208/feba09ff-bb4c-4e2c-8e2d-fcf7506310f6)

### Value of dashboard variable

        var appDataModule = angular.module("rewardsDataModule", []);

        var areaConfig = {
            areaPrefix: "Rewards",
            serviceEndpointRoot: "/api/",
            templateRoot: "/Areas/Rewards/ScriptsOneUI/Components/",
            testHooksAllowed: false,
            testHookQueryParams: {},
            punchCardUrlFormat: "/dashboard/{0}",
            isMobileViewModeEnabled: true,
            showDebugInfo: false,            
            catalogItemImg: "//az15297.vo.msecnd.net/images/rewards/rc/{0}",
            isVisualParityTest: false,
            useNewDBS: false,
            raDbsEnabled: true,
        };

**Comment by charlesbel** [comment]
Please show you accounts.json file, it seems it's malformed

**Comment by charlesbel** [comment]
> Please show you accounts.json file, it seems it's malformed

I mean redacting your emails and passwords but showing the structure of the file.

**Comment by SafwanWilson** [comment]
> 

HEllo sir sorry for late 


![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/89034208/c38e0a21-a9dc-4597-92c6-d70fb554b8ca)

**Comment by SafwanWilson** [comment]
FIXED
