### ISSUE TITLE
[BUG] json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by Wans22** [charlesbel/Microsoft-Rewards-Farmer#290]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

I didn't found any error like this one on the issues (I think)
Normally, the installation is done, the requirements installed, the accounts file edited and Im not using proxy

### Copy and paste your error

❯ python main.py
Traceback (most recent call last):
  File "C:\Users\Wan_s\desktop\Microsoft-Rewards-Farmer-master\main.py", line 175, in <module>
    main()
  File "C:\Users\Wan_s\desktop\Microsoft-Rewards-Farmer-master\main.py", line 21, in main
    loadedAccounts = setupAccounts()
                     ^^^^^^^^^^^^^^^
  File "C:\Users\Wan_s\desktop\Microsoft-Rewards-Farmer-master\main.py", line 118, in setupAccounts
    loadedAccounts = json.loads(accountPath.read_text(encoding="utf-8"))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 5 column 5 (char 95)

### Screenshots

![Capture d’écran (39)](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/82324747/e060eb4e-27e5-4096-9b86-9b421271f7fc)

### Value of dashboard variable

It doesn't even connect to the dashboard page so don't need this section

**Comment by charlesbel** [comment]
Looks like you malformed your accounts.json file, please make sure it is correct
