### ISSUE TITLE
Undetected Chrome Driver doesn't support Chrome 116

### ISSUE THREAD

**Issue by shopbuy11** [charlesbel/Microsoft-Rewards-Farmer#297]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

Sorry if this is a dumb question - how do I update the Undetected Chromedriver to 116?  The bot ran fine until today, when the following error started happening.   I guess Chrome must have updated.

### Copy and paste your error

selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:56193
from session not created: This version of ChromeDriver only supports Chrome version 114
Current browser version is 116.0.5845.97

### Screenshots

![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/136040705/a4f994e0-4362-45a7-8432-39b288eb0e17)

### Value of dashboard variable

https://gist.github.com/shopbuy11/a8417970aaa4a3a98621ef9afdb7602f

**Comment by theskid31** [comment]
hello i used this fork by jdholtz and it fixed this isuue ,uninstal it first
[https://github.com/ultrafunkamsterdam/undetected-chromedriver/pull/1478#issuecomment-1680979672](url)

**Comment by SvenQ32** [comment]
could the link be broken?

**Comment by charlesbel** [comment]
> could the link be broken?
> 

It's no longer

**Comment by shopbuy11** [comment]
Sorry I must have done something wrong.  When I ran the pip install command for the fork, I keep getting an error.  Also, if I browse to the https: address inside that command, I get "not Found".   Is the link broken as @SvenQ32  mentioned?  

![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/136040705/c31903cf-f78e-4f5d-8bb9-ce3b7f9b3ad9)

Looks like the fork changed patcher.py file, so I also tried replacing that file in my Undetected ChromeDriver folder before running PIP Install command to install, but it still didn't help with my issue at all.  

Help please if you can.  Thanks in advance.

**Comment by shopbuy11** [comment]
I think I figured it out.   For my own note in the future in case it comes up and for others dumb like me:

1. Install Git for Windows from here - https://git-scm.com/download/win, accepting all default options
2. Go to your Windows Start menu and look for Git CMD
3. In the Git CMD window, change directory to where you have the python stuff, then run the pip install command from the fork.
