### ISSUE TITLE
Add possible languages and geolocation in README 

### ISSUE THREAD

**Issue by riahc3** [charlesbel/Microsoft-Rewards-Farmer#299]
Hello

The readme does not specify the languages and geolocations.

For exmaple:

gsw-u-sd-chzh represents Swiss German in the Canton of Zürich

Which is the correct ones?

**Comment by charlesbel** [comment]
2 letter codes for language et locations
ex :
Languages : en,fr,de,es...
Locations : US,MX,GB,FR

In your case location should be CH and the language you want: fr,de...

**Comment by riahc3** [comment]
You gotta put some more examples in your documentation (not in a issue) on how it would be in the command line. I specified ONE example.
