### ISSUE TITLE
script.py closes instantly

### ISSUE THREAD

**Issue by Robi2003** [charlesbel/Microsoft-Rewards-Farmer#3]
I edited script.py with my account details and installed selenium.
When I start script.py it will show up just for less than a second and it is closed.

**Comment by charlesbel** [comment]
What is the error message ?

**Comment by Robi2003** [comment]
There is no error message.
There is just for less than a second a cmd window and it closes instantly

**Comment by charlesbel** [comment]
Run it with the command in cmd :
python script.py
That will output a message and avoid closing the window

**Comment by Robi2003** [comment]
![grafik](https://user-images.githubusercontent.com/21022093/94264123-6bcaef80-ff36-11ea-9daf-cffd36c00fbd.png)

Chrome is installed, I downloaded chrome webdriver manager... okay... but what to do with it? just start?

**Comment by charlesbel** [comment]
Hi,

I made some updates on the script, does it works well now ?

**Comment by charlesbel** [comment]
Hi, I juste made a major update, let me know if you have more problems
