### ISSUE TITLE
Main.py is not longer executing

### ISSUE THREAD

**Issue by TimNick151297** [charlesbel/Microsoft-Rewards-Farmer#304]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

I updated to the latest release via auto update and main.py is stopping without further execution. I also installed fresh from github.

### Copy and paste your error

PS C:\Users\XXXX> S:\Desktop\Microsoft-Rewards-Farmer-master\main.py
Traceback (most recent call last):
  File "S:\Desktop\Microsoft-Rewards-Farmer-master\main.py", line 9, in <module>
    from src import Browser, DailySet, Login, MorePromotions, PunchCards, Searches
  File "S:\Desktop\Microsoft-Rewards-Farmer-master\src\__init__.py", line 1, in <module>
    from .browser import Browser
  File "S:\Desktop\Microsoft-Rewards-Farmer-master\src\browser.py", line 9, in <module>
    import seleniumwire.undetected_chromedriver as webdriver
ModuleNotFoundError: No module named 'seleniumwire'

### Screenshots

Same output as shown above

### Value of dashboard variable

<script src="https://gist.github.com/TimNick151297/02213a4e3c02d8a4e90417aeb32da417.js"></script>

**Comment by klept0** [comment]
try and "pip install seleniumwire" if you don't have it installed

**Comment by TimNick151297** [comment]
Yep, that fixed it. For some reason, it did not install selenium-wire from the requirements.txt. Thanks!

**Comment by TimNick151297** [comment]
Issue closed
