### ISSUE TITLE
Redeeming causes account restriction

### ISSUE THREAD

**Issue by idwys** [charlesbel/Microsoft-Rewards-Farmer#308]
the automatic bing search is being detected as unusual use and therefore the account is being restricted when trying to redeem gift cards...

answer from microsoft support:
Please be informed that an individual user must manually enter a text for the good faith purpose of obtaining Bing search results for such user's own research purposes and does not include any query entered by a bot, macro, or other automated or fraudulent means of any kind. The restrictions on your Rewards account will be automatically lifted in the coming days when a more genuine search behavior is detected

is there any solution in getting the bing searches more common to a "normal use"?

**Comment by bobdabear** [comment]
this might be solved with [#282](https://github.com/charlesbel/Microsoft-Rewards-Farmer/issues/282)

**Comment by idwys** [comment]
i solved it by disabling the search function and waiting a couple of days. After that i was able to redeem a gift card
