### ISSUE TITLE
skipping supersonic quiz[BUG]

### ISSUE THREAD

**Issue by njhughesSAS** [charlesbel/Microsoft-Rewards-Farmer#31]
**Error Log**
Paste the error log here.
No error item is skips
**Screenshot of the page**
Add a screenshot of the page where the error apeared.
![image](https://user-images.githubusercontent.com/69064506/107407634-c23c6300-6abe-11eb-829c-cf6984ca068d.png)

**Source code of dashboard**
Copy the source code of the [Microsoft Rewards Dashboard Page](https://account.microsoft.com/rewards) and paste it on [Gist](https://gist.github.com). Then share me the link of the gist here.
here is the xpath for the missed item `//*[@id="daily-sets"]/mee-card-group[1]/div/mee-card[2]/div/card-content/mee-rewards-daily-set-item-content/div/div[3]/a/span/ng-transclude`
here is the full source
https://gist.github.com/njhughesSAS/0e4ac57d3b24fb520ebfb6ac21ba8445

**Comment by charlesbel** [comment]
Okay, so edit line 735 : change True to False
So this will disable the headless mode, could you run it again and check if it is really skipped, or if the bot go on and fail inside the quiz ?

**Comment by charlesbel** [comment]
I deployed a fix, try it !
