### ISSUE TITLE
ModuleNotFoundError: No module named 'ipapi

### ISSUE THREAD

**Issue by sea-pirate** [charlesbel/Microsoft-Rewards-Farmer#32]
I ran `pip install -r requirements.txt` and then `python3 ms_rewards_farmer.py` and got the following error:
```
Traceback (most recent call last):
  File "ms_rewards_farmer.py", line 7, in <module>
    import ipapi
ModuleNotFoundError: No module named 'ipapi'
```
I have `ipapi` installed (per requirements.txt) and haven't used it much but looks like it's deprecated in favor of `Ipython.core.ipapi`...

---
Raspberry Pi 3 Model B Plus Rev 1.3p running Raspbian GNU/Linux 10 (buster)

**Comment by charlesbel** [comment]
The package seems updated : https://pypi.org/project/ipapi/#history
Maybe try to update pip and python and try again

**Comment by sea-pirate** [comment]
Got it, thank you!

Note for RPi users that may come across this: If you don't have Homebrew, use `sudo apt-get install chromium-chromedriver` to install the chromedriver instead.
