### ISSUE TITLE
[BUG] Login failure ignored

### ISSUE THREAD

**Issue by sea-pirate** [charlesbel/Microsoft-Rewards-Farmer#33]
Whenever an incorrect username or password is inputted, the program continues going through its list and does not throw an error or realize what went wrong.

![image](https://user-images.githubusercontent.com/78832349/107840726-cdbbb280-6d7a-11eb-8169-7f1a7b8270d4.png)

**Comment by charlesbel** [comment]
Yup, the bot suppose the account credentials are correct, so just add correct credentials.
