### ISSUE TITLE
Too many searches[BUG]

### ISSUE THREAD

**Issue by raphalation** [charlesbel/Microsoft-Rewards-Farmer#34]
For some reason, the program is trying to do way too many searches. As you can see in the picture, it has done all the desktop searches already but is still only on 40/210. This means it takes ages to finish. 

**Error Log**
DevTools listening on ws://127.0.0.1:56383/devtools/browser/54ddae38-3812-4919-9183-54eb7a071fc1
[LOGIN] Logging-in...
[LOGIN] Writing email...
[LOGIN] Writing password...
[LOGIN] Passing security checks...
[LOGIN] Logged-in !
[LOGIN] Ensuring login on Bing...
←[92m[LOGIN] Logged-in successfully !←[00m
←[92m[POINTS] You have 34288 points on your account !←[00m
[DAILY SET] Trying to complete the Daily Set...
←[92m[DAILY SET] Completed the Daily Set successfully !←[00m
[PUNCH CARDS] Trying to complete the Punch Cards...
←[92m[PUNCH CARDS] Completed the Punch Cards successfully !←[00m
[MORE PROMO] Trying to complete More Promotions...
←[92m[MORE PROMO] Completed More Promotions successfully !←[00m
[BING] Starting Desktop and Edge Bing searches...
[BING] 1/210
[BING] 2/210
[BING] 3/210
[BING] 4/210
[BING] 5/210
[BING] 6/210
[BING] 7/210
[BING] 8/210
[BING] 9/210
[BING] 10/210
[BING] 11/210
[BING] 12/210
[BING] 13/210
[BING] 14/210
[BING] 15/210
[BING] 16/210
[BING] 17/210
[BING] 18/210
[BING] 19/210
[BING] 20/210
[BING] 21/210
[BING] 22/210
[BING] 23/210
[BING] 24/210
[BING] 25/210
[BING] 26/210
[BING] 27/210
[BING] 28/210
[BING] 29/210
[BING] 30/210
[BING] 31/210
[BING] 32/210
[BING] 33/210
[BING] 34/210
[BING] 35/210
[BING] 36/210
[BING] 37/210
[BING] 38/210
[BING] 39/210
[BING] 40/210
[BING] 41/210
[BING] 42/210
[BING] 43/210
[BING] 44/210
[BING] 45/210
etc
**Screenshot of the page**
![Capture1](https://user-images.githubusercontent.com/29611498/107851090-35b3dc80-6dff-11eb-8e0c-d2c165641e9f.PNG)

**Source code of dashboard**
https://gist.github.com/raphalation/b409ac17c1366789daa843aff62d9801

**Comment by charlesbel** [comment]
I fixed it, download the latest version. Infact this error was because Microsoft is currently changing the number of searches you should be able to do, but not for everyone like said in this article : https://www.onmsft.com/news/microsoft-appears-to-be-beta-testing-big-changes-to-points-earnings-in-microsoft-rewards-to-put-more-emphasis-on-using-edge
