### ISSUE TITLE
[BUG] infinite loading chrome page

### ISSUE THREAD

**Issue by DarkFlyper** [charlesbel/Microsoft-Rewards-Farmer#354]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

It gets stuck on logging in and the webpage stays stuck on loading

### Copy and paste your error

No terminal error

### Screenshots

![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/99375543/adca8585-fe97-4d64-a19c-2b3594823c91)

### Value of dashboard variable

none

**Comment by DarkFlyper** [comment]
after like 5 minutes it changed to this 
![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/99375543/9edb1a8c-b5da-468c-8356-8442c78ca98d)

**Comment by DarkFlyper** [comment]
Did some testing and found out it lets me access any website except for login.live.com

**Comment by DarkFlyper** [comment]
After clearing the sessions folder I was stuck on this screen
![Screenshot 2023-09-16 222653](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/99375543/419cef5d-9e4f-4fbe-9ca6-108d16c977ad)
Basically its after the password and idk how to fix

**Comment by evox45** [comment]
Exact same problem I have.

**Comment by shopbuy11** [comment]
Same here.  Looks like https://login.live.com is acting up, because it does the same when I try manually.

However, logging in to the MS Rewards site works because the URL for https://login.live.com is very long.  If I put that long URL in the login.py instead of https://login.live.com, I see that it does log into the rewards site.   But then, after that, the bot doesn't do anything.

**Comment by DarkFlyper** [comment]
Yo do I don't rlly understand what you mean by long url and short url so maybe you can like détail it more

**Comment by DarkFlyper** [comment]
MANNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN why is this project dead its so sad

**Comment by shopbuy11** [comment]
I don't think it's dead.   Keep in mind that @charlesbel  is doing this for us free of charge.   I appreciate whatever I can get from it very much.    If he is too busy, that's just how it is and we should just accept it.

**Comment by Natriumpikant** [comment]
Same like this thread i think.. 
https://github.com/charlesbel/Microsoft-Rewards-Farmer/issues/352

**Comment by DarkFlyper** [comment]
Yeah but even then it's still doesn't resolve my issue
