### ISSUE TITLE
Feature Request: Docker Image

### ISSUE THREAD

**Issue by JoshuaGarrison27** [charlesbel/Microsoft-Rewards-Farmer#36]
I think this would be prefect for running in docker. Especially if you can figured out some small details.

Suggestion for features for a docker image:

- [ ] Docker Hub Image (for easy access for someone just wanting to run it)
- [ ] Expose settings in a config file or as environment variables for Cron settings and Accounts

I wish I could create a PR for you but I don't have a lot of experience with Python or creating public Docker images

**Comment by JoshuaGarrison27** [comment]
Added a pull request for this ( #38 )

I could not find a good library for a traditional cron string (ie 5 4 * * *) that I could fully understand but I did find a small simple solution.

**Comment by charlesbel** [comment]
I will review your pull request 👍 thanks
