### ISSUE TITLE
[BUG] So this program creates google apps EVERY time it gets runned

### ISSUE THREAD

**Issue by DarkFlyper** [charlesbel/Microsoft-Rewards-Farmer#366]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

Well every time you run the program its going to create a gmail, youtube, slides and sheets app

### Copy and paste your error

Well every time you run the program its going to create a gmail, youtube, slides and sheets app

### Screenshots

![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/99375543/17877093-d285-4694-b988-e4a55ae197ba)
![image](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/99375543/7640427f-6500-45b5-bddb-2af096d5ab54)

### Value of dashboard variable

None

**Comment by Infern0Tempest** [comment]
Could you provide the path in which you found them, I scanned all of my drives and only seemed to come up with a couple of .ico files located inside the program folder

**Comment by DarkFlyper** [comment]
Yeah so I dont know how to get the path of a app in control panel

**Comment by riahc3** [comment]
This project is dead so

**Comment by klept0** [comment]
Each time you delete sessions it makes a new one...

**Comment by DarkFlyper** [comment]
> Each time you delete sessions it makes a new one...

But who said that im deleting sessions

**Comment by klept0** [comment]
I would suggest providing more information - also you provided little to no information in the beginning then reply back with something crass - don't expect more help from others in the future

**Comment by DarkFlyper** [comment]
> I would suggest providing more information - also you provided little to no information in the beginning then reply back with something crass - don't expect more help from others in the future

What info do you want me to give like it's a super wierd issue what do you want more other than when you run it creates little Google app shortcuts. They don't take space or anything

**Comment by Flojomojo** [comment]
> > I would suggest providing more information - also you provided little to no information in the beginning then reply back with something crass - don't expect more help from others in the future
> 
> What info do you want me to give like it's a super wierd issue what do you want more other than when you run it creates little Google app shortcuts. They don't take space or anything

Where are the shortcuts created? Like on your desktop or in the bot folder?

**Comment by DarkFlyper** [comment]
> > > I would suggest providing more information - also you provided little to no information in the beginning then reply back with something crass - don't expect more help from others in the future
> 
> > 
> 
> > What info do you want me to give like it's a super wierd issue what do you want more other than when you run it creates little Google app shortcuts. They don't take space or anything
> 
> 
> 
> Where are the shortcuts created? Like on your desktop or in the bot folder?

They are found in the shortcuts folder of windows but only one of them. In control panel you will see multiple of them which am assuming are related to the bot opening a chrome tab

**Comment by Willxwisp** [comment]
> > > > I would suggest providing more information - also you provided little to no information in the beginning then reply back with something crass - don't expect more help from others in the future
> > 
> > 
> > > 
> > 
> > 
> > > What info do you want me to give like it's a super wierd issue what do you want more other than when you run it creates little Google app shortcuts. They don't take space or anything
> > 
> > 
> > Where are the shortcuts created? Like on your desktop or in the bot folder?
> 
> They are found in the shortcuts folder of windows but only one of them. In control panel you will see multiple of them which am assuming are related to the bot opening a chrome tab

Try to use Farshad Zargar's REward Farmer on Gitlab it works better plus no problem when it comes to timeout errors

**Comment by DarkFlyper** [comment]
> > > > > I would suggest providing more information - also you provided little to no information in the beginning then reply back with something crass - don't expect more help from others in the future
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > What info do you want me to give like it's a super wierd issue what do you want more other than when you run it creates little Google app shortcuts. They don't take space or anything
> 
> > > 
> 
> > > 
> 
> > > Where are the shortcuts created? Like on your desktop or in the bot folder?
> 
> > 
> 
> > They are found in the shortcuts folder of windows but only one of them. In control panel you will see multiple of them which am assuming are related to the bot opening a chrome tab
> 
> 
> 
> Try to use Farshad Zargar's version on Gitlab it works better plus no problem when it comes to timeout errors

I only found one made by Tom maybe you can give me a link

**Comment by riahc3** [comment]
> > > > > I would suggest providing more information - also you provided little to no information in the beginning then reply back with something crass - don't expect more help from others in the future
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > What info do you want me to give like it's a super wierd issue what do you want more other than when you run it creates little Google app shortcuts. They don't take space or anything
> > > 
> > > 
> > > Where are the shortcuts created? Like on your desktop or in the bot folder?
> > 
> > 
> > They are found in the shortcuts folder of windows but only one of them. In control panel you will see multiple of them which am assuming are related to the bot opening a chrome tab
> 
> Try to use Farshad Zargar's version on Gitlab it works better plus no problem when it comes to timeout errors

This one is dead too

**Comment by DarkFlyper** [comment]
> > > > > > I would suggest providing more information - also you provided little to no information in the beginning then reply back with something crass - don't expect more help from others in the future
> 
> > > > 
> 
> > > > 
> 
> > > > > 
> 
> > > > 
> 
> > > > 
> 
> > > > > What info do you want me to give like it's a super wierd issue what do you want more other than when you run it creates little Google app shortcuts. They don't take space or anything
> 
> > > > 
> 
> > > > 
> 
> > > > Where are the shortcuts created? Like on your desktop or in the bot folder?
> 
> > > 
> 
> > > 
> 
> > > They are found in the shortcuts folder of windows but only one of them. In control panel you will see multiple of them which am assuming are related to the bot opening a chrome tab
> 
> > 
> 
> > Try to use Farshad Zargar's version on Gitlab it works better plus no problem when it comes to timeout errors
> 
> 
> 
> This one is dead too

So theres no alternatives

**Comment by Flojomojo** [comment]
Im currently developing an alternative, if noone else releases one within next few days, i will publicise it.

**Comment by DarkFlyper** [comment]
> Im currently developing an alternative, if noone else releases one within next few days, i will publicise it.

You should publish it

**Comment by Willxwisp** [comment]
> > > > > > I would suggest providing more information - also you provided little to no information in the beginning then reply back with something crass - don't expect more help from others in the future
> > > > 
> > > > 
> > > > > 
> > > > 
> > > > 
> > > > > What info do you want me to give like it's a super wierd issue what do you want more other than when you run it creates little Google app shortcuts. They don't take space or anything
> > > > 
> > > > 
> > > > Where are the shortcuts created? Like on your desktop or in the bot folder?
> > > 
> > > 
> > > They are found in the shortcuts folder of windows but only one of them. In control panel you will see multiple of them which am assuming are related to the bot opening a chrome tab
> > 
> > 
> > Try to use Farshad Zargar's version on Gitlab it works better plus no problem when it comes to timeout errors
> 
> This one is dead too

I mean you literally just update the user agents and baam

**Comment by riahc3** [comment]
> Im currently developing an alternative, if noone else releases one within next few days, i will publicise it.

Thank you. Its much appriciated.
