### ISSUE TITLE
[Bug] This version of ChromeDriver only supports Chrome version 118 Current browser version is 117.0.5938.152

### ISSUE THREAD

**Issue by SgtSobieski** [charlesbel/Microsoft-Rewards-Farmer#376]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

Well its most obvious, but the regular steps havent worked for me.

Regular stepts I know:
- uninstall, install and/or update chromedriver-undetected
- download newest chromedriver manually and add into path

Hope somebody could help one last time, as this issue obviously comes up with every update. 

Thanks in advance!

### Copy and paste your error

This version of ChromeDriver only supports Chrome version 118
Current browser version is 117.0.5938.152

### Screenshots

![Unbenannt](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/125480018/09975918-b710-4c82-bcbd-2b3669ba2004)

### Value of dashboard variable

[There is no such line]

**Comment by klept0** [comment]
Step 1: UPDATE YOUR BROWSER
Step 2: Close this issue

**Comment by Shadie116** [comment]
thought that was  an ip adress
