### ISSUE TITLE
[BUG] 2 Factor Auth causes it to get stuck at "Ensuring login on Bing"

### ISSUE THREAD

**Issue by shinji257** [charlesbel/Microsoft-Rewards-Farmer#39]
**Error Log**
There is no error.  It just never goes through.

**Screenshot of the page**
Sorry.  I forgot to get a screenshot but I disabled headless mode and found it was stopping at a 2 factor authentication prompt.  Manually entering the auth code here allowed it to proceed.

**Source code of dashboard**
It's the 2 factor screen.  I'll see if I can get it later.

This issue affects accounts where 2 factor is enabled.

**Comment by charlesbel** [comment]
I would recommend to disable it... Just because it is a bot, so this is useless if you have to enter manually the code...

**Comment by shinji257** [comment]
This was more to make people aware but at least one other script I saw had an option for 2 factor and it basically just shut off headless mode because that's the only real way past it.  Probably should be doing this on a dummy account anyways...

**Comment by LeVraiRoiDHyrule** [comment]
> 
> 
> This was more to make people aware but at least one other script I saw had an option for 2 factor and it basically just shut off headless mode because that's the only real way past it. Probably should be doing this on a dummy account anyways...

What script are you talking about ?
