### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by ohioohio** [charlesbel/Microsoft-Rewards-Farmer#391]
Can someone please support me on discord as I do not understand this at all

**Comment by pierrelasse** [comment]
You need to download the code, ensure you are able to run the code, add your login details for your microsoft account, run the program. :^D

**Comment by ohioohio** [comment]
> You need to download the code, ensure you are able to run the code, add your login details for your microsoft account, run the program. :^D

I did that can you help me on discord, no need to call you can just message me what to do. My user is catv4best
send me a friend request and i will accept it

**Comment by bruno-lambreht** [comment]
1. Install VSCode
2. Download the file
3. Extract
4. Open the folder in VSCode
5. Install the Python 3.11 from MS Store and install modules in VSCode Terminal: https://imgur.com/a/Cyf6usq
6. Go to "accounts.json.example" and remove ".example" from the file
7. In accounts.json, add your login details following the example
8. Run main.py file by clicking in "play" icon: https://imgur.com/a/FJD7aqE

Fine!

**Comment by sleepyslair** [comment]
i dont understand step 8 with imgur, why do you need to use the site

**Comment by ohioohio** [comment]
> 1. Install VSCode
> 2. Download the file
> 3. Extract
> 4. Open the folder in VSCode
> 5. Install the Python 3.11 from MS Store and install modules in VSCode Terminal: https://imgur.com/a/Cyf6usq
> 6. Go to "accounts.json.example" and remove ".example" from the file
> 7. In accounts.json, add your login details following the example
> 8. Run main.py file by clicking in "play" icon: https://imgur.com/a/FJD7aqE
> 
> Fine!

ty but I'm still confused about this http://user:pass@host1:port

**Comment by sleepyslair** [comment]
> 1. Install VSCode
> 2. Download the file
> 3. Extract
> 4. Open the folder in VSCode
> 5. Install the Python 3.11 from MS Store and install modules in VSCode Terminal: https://imgur.com/a/Cyf6usq
> 6. Go to "accounts.json.example" and remove ".example" from the file
> 7. In accounts.json, add your login details following the example
> 8. Run main.py file by clicking in "play" icon: https://imgur.com/a/FJD7aqE
> 
> Fine!

How would i fix this?
  File "c:\Users\admin\Downloads\main.py", line 9, in <module>
    from src import Browser, DailySet, Login, MorePromotions, PunchCards, Searches
ModuleNotFoundError: No module named 'src'

**Comment by ohioohio** [comment]
> > 1. Install VSCode
> > 2. Download the file
> > 3. Extract
> > 4. Open the folder in VSCode
> > 5. Install the Python 3.11 from MS Store and install modules in VSCode Terminal: https://imgur.com/a/Cyf6usq
> > 6. Go to "accounts.json.example" and remove ".example" from the file
> > 7. In accounts.json, add your login details following the example
> > 8. Run main.py file by clicking in "play" icon: https://imgur.com/a/FJD7aqE
> > 
> > Fine!
> 
> How would i fix this? File "c:\Users\admin\Downloads\main.py", line 9, in from src import Browser, DailySet, Login, MorePromotions, PunchCards, Searches ModuleNotFoundError: No module named 'src'

I think install src

**Comment by ohioohio** [comment]
I understood
