### ISSUE TITLE
[BUG] send log to webhook (discord)

### ISSUE THREAD

**Issue by neve360** [charlesbel/Microsoft-Rewards-Farmer#396]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

i added like some issues said -vn to send log to webhook but its saying this:

usage: main.py [-h] [-v] [-l LANG] [-g GEO] [-p PROXY] [-t TOKEN CHAT_ID] [-d DISCORD]
main.py: error: argument -v/--visible: ignored explicit argument 'n'

### Copy and paste your error

usage: main.py [-h] [-v] [-l LANG] [-g GEO] [-p PROXY] [-t TOKEN CHAT_ID] [-d DISCORD]
main.py: error: argument -v/--visible: ignored explicit argument 'n'

### Screenshots

usage: main.py [-h] [-v] [-l LANG] [-g GEO] [-p PROXY] [-t TOKEN CHAT_ID] [-d DISCORD]
main.py: error: argument -v/--visible: ignored explicit argument 'n'

### Value of dashboard variable

not that problem

**Comment by ExtremeMemes** [comment]
I believe verbose messages are not enabled in this repo. Someone might have made a fork and enabled the -vn flag for logs to discord. It is saying that because there is an argument for -v, but there is none for -vn.
