### ISSUE TITLE
Ban wave?

### ISSUE THREAD

**Issue by binhphuon** [charlesbel/Microsoft-Rewards-Farmer#411]
Mcs changed something in their detector that made all my account banned

If any of you haven't been banned yet. Could you answer some of my questions?

1. What is your recovery mail's host? (Could be gmail.com , mailforspam.com ,......)
- Mine is mailforspam.com and it's banned

2. Does your account name similar to your account's mail?
- Mine doesn't (look the image)

3. How many rewards account you use per household/ip
- Mine is 6 because maximum is 6

4. How many time you run your bot a day?
- For me, It starts automatically 4 times a day

5. Are you farming in US?
- For me, yes

6. Does your account have a phone number?
- Mine doesn't 

7. How many points you have right now?
- Mine was 8k before it's banned

![Screenshot_20231201-074916_Microsoft Remote Desktop](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/131878934/3c218bee-86d2-4969-9b8a-08b9c8ea631a)

**Comment by paul0665** [comment]
Dont use mailforspam, that will get you ban easy.
Use gmail.
