### ISSUE TITLE
[Question] Cron Job schduling

### ISSUE THREAD

**Issue by njhughesSAS** [charlesbel/Microsoft-Rewards-Farmer#42]
I cannot seem to get cronjob scheduling working with chromedriver. 
I don't see any obvious errors in the syslog. 
here is my cron job setup
`00 10 * * * python3 /path/to/rewards/farmer.py >> /home/log/rbots.txt`
I have also tried 
`00 10 * * * export DISPLAY=:0; python3 /path/to/rewards/farmer.py >> /home/log/rbots.txt`
here is my log output
https://gist.github.com/njhughesSAS/d5362ae29c0dae2c7e10c8808713cde8
does anyone have cron working with chromedriver

**Comment by charlesbel** [comment]
Does it works well outside?

**Comment by njhughesSAS** [comment]
Yea works fine as that user all the PATH are set chromedriver is in usr/local/bin it's quite puzzling I can also get none selieum based py scripts to works just fine it has something to do with Selenium and chromedriver

**Comment by shinji257** [comment]
Try wrapping it in a script.  That's what I do currently as I have it posting the log to discord via a webhook at the moment.

**Comment by njhughesSAS** [comment]
> Try wrapping it in a script. That's what I do currently as I have it posting the log to discord via a webhook at the moment.

This is the working solution we might want to add this to the read me. If end users set up the PATH for chromedriver it should pretty similar bash for all users
