### ISSUE TITLE
For those who have 404 error when running script, CHECK THIS

### ISSUE THREAD

**Issue by Emrys-Lee-XD** [charlesbel/Microsoft-Rewards-Farmer#442]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

Use Win+R to run
 %LOCALAPPDATA%\Programs\Python\**PythonVERSION**\Lib\site-packages
change PythonVERSION to your version like Python38, Python311,etc.
Then find
patcher.py
Open it with notpad o any coding program like Visual Studio Code
Using Ctrl+F find
download_url = "https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/%s/%s/%s"
should be in line 283
then replace it with
download_url = "https://storage.googleapis.com/chrome-for-testing-public/%s/%s/%s"
save and quit
run script as usual

### Copy and paste your error

Credit to @klept0 and @dudeua

### Screenshots

![屏幕截图 2024-02-17 095420](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/128412481/bae072d2-73b1-4fa2-b2df-d8567d9efe61)
![屏幕截图 2024-02-17 100047](https://github.com/charlesbel/Microsoft-Rewards-Farmer/assets/128412481/60f79a4f-f805-4bf1-82cb-dc9bcf0e44f4)

### Value of dashboard variable

none

**Comment by paul0665** [comment]
already reported #439

**Comment by Emrys-Lee-XD** [comment]
most people don't check closed issues, I keep it open and on top so people can see the solution at first sight.

**Comment by deswong** [comment]
This has been fixed in undetected-chromedriver version 3.5.5

**Comment by deswong** [comment]
PR raised to resolve issue.

**Comment by klept0** [comment]
The original repo is not being maintained as far as we can tell hence why I started mine. Feel free to look at it and make any PR that is necessary

**Comment by Smyntix** [comment]
set up everything, but when i run "main" it automatically closes.
when i tried this method, i couldn't find patcher.py...

**Comment by klept0** [comment]
> set up everything, but when i run "main" it automatically closes. when i tried this method, i couldn't find patcher.py...

[https://github.com/klept0/MS-Rewards-Farmer](https://github.com/klept0/MS-Rewards-Farmer)

**Comment by Emrys-Lee-XD** [comment]
I'm gonna close it. the problem should be already fixed anyway.
If anyone has other problem check 
https://github.com/klept0/MS-Rewards-Farmer

**Comment by Smyntix** [comment]
> > set up everything, but when i run "main" it automatically closes. when i tried this method, i couldn't find patcher.py...
> 
> https://github.com/klept0/MS-Rewards-Farmer

Will try it tomorrow…
