### ISSUE TITLE
Closes near instantly 

### ISSUE THREAD

**Issue by Saileyy** [charlesbel/Microsoft-Rewards-Farmer#45]
A few seconds after the window opens it closes, this only started today.

![image](https://user-images.githubusercontent.com/76251597/109862042-e28fb580-7c57-11eb-867e-47df747a4ffd.png)

**Comment by charlesbel** [comment]
What's the error ?

**Comment by Saileyy** [comment]
The error is that it just closes a few seconds after launching the program. There's no displayed error message it just closes before it can do anything.

**Comment by WhiskeyDent** [comment]
Same problem, started today

**Comment by charlesbel** [comment]
Why did you not tried `python3 script.py` to get the error log ?

**Comment by UnknownGreen** [comment]
I have this problem as well but before it crashes this is what it shows me 
![image](https://user-images.githubusercontent.com/61893282/110131220-d6c00280-7dc1-11eb-9874-b4d594137582.png)
![image](https://user-images.githubusercontent.com/61893282/110131237-da538980-7dc1-11eb-9f96-3fe61615edc7.png)
(usually, it closes too fast to be readable or take a screenshot of it but you can do it if you record it then slow it down in premier)

**Comment by Saileyy** [comment]
> (usually, it closes too fast to be readable or take a screenshot of it but you can do it if you record it then slow it down in premier)

thats a good idea i didnt think of that. But as you can see multiple people are having this issue

**Comment by charlesbel** [comment]
> I have this problem as well but before it crashes this is what it shows me 
> ![image](https://user-images.githubusercontent.com/61893282/110131220-d6c00280-7dc1-11eb-9874-b4d594137582.png)
> ![image](https://user-images.githubusercontent.com/61893282/110131237-da538980-7dc1-11eb-9f96-3fe61615edc7.png)
> (usually, it closes too fast to be readable or take a screenshot of it but you can do it if you record it then slow it down in premier)

What append when you go to https://ipapi.co/json from the computer where you are running the script ?

**Comment by charlesbel** [comment]
> A few seconds after the window opens it closes, this only started today.
> 
> ![image](https://user-images.githubusercontent.com/76251597/109862042-e28fb580-7c57-11eb-867e-47df747a4ffd.png)
> 

It seems you have a different issue than the other users on this issue, what is your error log when you run the script from the terminal ?

**Comment by Saileyy** [comment]
From the terminal this happens when i run it 
![image](https://user-images.githubusercontent.com/76251597/110160382-dfc1cb80-7de3-11eb-92d1-51f3d9cadd5a.png)

**Comment by WhiskeyDent** [comment]
Updating my chromedriver worked for me, thanks

**Comment by koderian** [comment]
[DAILY SET] Trying to complete the Daily Set...
Traceback (most recent call last):
  File "ms_rewards_farmer.py", line 752, in <module>
    completeDailySet(browser)
  File "ms_rewards_farmer.py", line 451, in completeDailySet
    d = getDashboardData(browser)['dailySetPromotions']
  File "ms_rewards_farmer.py", line 447, in getDashboardData
    dashboard = json.loads(dashboard)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0) 

@charlesbel Started yesterday

**Comment by charlesbel** [comment]
> 
> [DAILY SET] Trying to complete the Daily Set...
> Traceback (most recent call last):
>   File "ms_rewards_farmer.py", line 752, in <module>
>     completeDailySet(browser)
>   File "ms_rewards_farmer.py", line 451, in completeDailySet
>     d = getDashboardData(browser)['dailySetPromotions']
>   File "ms_rewards_farmer.py", line 447, in getDashboardData
>     dashboard = json.loads(dashboard)
>   File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
>     return _default_decoder.decode(s)
>   File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0) 
> 
> @charlesbel Started yesterday

Make a new issue
