### ISSUE TITLE
Crashes right after starting

### ISSUE THREAD

**Issue by UnknownGreen** [charlesbel/Microsoft-Rewards-Farmer#46]
It's too fast for me to take a screenshot of the rest but this is what I was able to get
![image](https://user-images.githubusercontent.com/61893282/109995394-280abc00-7d06-11eb-839c-d0c8ec916d37.png)
I'm not sure how to fix that warning since I already had most of the requirements installed from other bots I've tried

**Comment by charlesbel** [comment]
As written in the README, you have to make a `pip install -r requierements.txt`

**Comment by UnknownGreen** [comment]
I did that but as I said they've been satisfied 
![image](https://user-images.githubusercontent.com/61893282/109996870-8b491e00-7d07-11eb-84ce-e0b136b0df0d.png)
so I'm not really sure what to do about this thank you for getting back to me

**Comment by charlesbel** [comment]
It can be solved by upgrading requests:
`pip install requests`

**Comment by UnknownGreen** [comment]
Thank you that did seem to fix that error but It still crashes after it displays my email and says listening on dev port, it's too fast to get an image of it so I'll get a video then capture the image from that

**Comment by UnknownGreen** [comment]
![image](https://user-images.githubusercontent.com/61893282/110005035-f7c81b00-7d0f-11eb-80b8-b099303c93ea.png)
I managed to take a picture of the video I took 
![image](https://user-images.githubusercontent.com/61893282/110005113-0a425480-7d10-11eb-9676-ea46cf596b8e.png)

**Comment by charlesbel** [comment]
What append when you go to https://ipapi.co/json from the computer where you are running the script ?

**Comment by UnknownGreen** [comment]
![image](https://user-images.githubusercontent.com/61893282/110162078-257f9380-7de6-11eb-95ca-2e6fe064f1ec.png)
(i got a VPN on but I tried it without it on and it still never worked got the same error)

**Comment by charlesbel** [comment]
> ![image](https://user-images.githubusercontent.com/61893282/110162078-257f9380-7de6-11eb-95ca-2e6fe064f1ec.png)
> (i got a VPN on but I tried it without it on and it still never worked got the same error)

If you have access to https://ipapi.co/json, the script should work... I am confused...

**Comment by UnknownGreen** [comment]
> 
> 
> > ![image](https://user-images.githubusercontent.com/61893282/110162078-257f9380-7de6-11eb-95ca-2e6fe064f1ec.png)
> > (i got a VPN on but I tried it without it on and it still never worked got the same error)
> 
> If you have access to https://ipapi.co/json, the script should work... I am confused...

updating the google drivers fixed it thank you :)
