### ISSUE TITLE
[BUG] Stuck on Ensuring login on bing

### ISSUE THREAD

**Issue by UnknownGreen** [charlesbel/Microsoft-Rewards-Farmer#50]
![image](https://user-images.githubusercontent.com/61893282/110219065-f3893280-7eb4-11eb-9d96-51b4dd2fc0e0.png)
I was timing to see how fast it could finish 19 new + one already done account but it got stuck on the second account it's been stuck on it for 10 minutes flat and still stuck I tried restarting it but I'm still stuck on the same issue (is this an issue because I have too many accounts in the file or anything to do with that because it worked before when I only had 5)

**Comment by charlesbel** [comment]
Update on line 735 from True to False to disable headless mode. See what is the problem.

**Comment by UnknownGreen** [comment]
> 
> 
> Update on line 735 from True to False to disable headless mode. See what is the problem.

Thank you i found out what the problem was and it isn't anything to do with the bot
