### ISSUE TITLE
[BUG]Bot Stuck on this or that

### ISSUE THREAD

**Issue by njhughesSAS** [charlesbel/Microsoft-Rewards-Farmer#53]
Looks like we are hanging on the 9th question for this or that is you manually answer does move on eventually but leaves the next quiz on screen while it does the searches. 
![image](https://user-images.githubusercontent.com/69064506/110345033-fd10b880-7fe2-11eb-9833-94714a7dc724.png)

**Comment by Killerherts** [comment]
Cannot recreate issue not sure what happened

**Comment by charlesbel** [comment]
So, I don't know too where is the problem, it could be at any time in a this or that, I'm a bit confused...
