### ISSUE TITLE
Random account execution order

### ISSUE THREAD

**Issue by koderian** [charlesbel/Microsoft-Rewards-Farmer#56]
Feature request: make account run rather from top to bottom run randomly.

**Comment by Twisted-Remedy** [comment]
What's the format for multiple accounts?

**Comment by koderian** [comment]
Just add multiple entries in the accounts.json file (you'll need to remove the .sample)

**Comment by charlesbel** [comment]
> Feature request: make account run rather from top to bottom run randomly. 

Od you think random.shuffle ([https://www.w3schools.com/python/ref_random_shuffle.asp](w3schools exeample)) could do the job ?

**Comment by koderian** [comment]
Yes that should work. You could just leave the accounts.json as is and let the Python script randomize it at the account variable calltime using the random.shuffle function (or rand.sample, although that is deprecated in Python 3.9)

**Comment by Twisted-Remedy** [comment]
How do I put it inside the json file, that's for 1 but I don't know the format for 2
[
    {
        "username": "Email@gmail.com",
        "password": "password"
    }
]

**Comment by charlesbel** [comment]
> Yes that should work. You could just leave the accounts.json as is and let the Python script randomize it at the account variable calltime using the random.shuffle function (or rand.sample, although that is deprecated in Python 3.9)

I added the feature

**Comment by charlesbel** [comment]
> How do I put it inside the json file, that's for 1 but I don't know the format for 2
> [
> {
> "username": "[Email@gmail.com](mailto:Email@gmail.com)",
> "password": "password"
> }
> ]

It's a list of dictionaries, if you still don't understand, refer to the docs : https://docs.python.org/3/tutorial/datastructures.html
