### ISSUE TITLE
Implement logging and log files

### ISSUE THREAD

**Issue by koderian** [charlesbel/Microsoft-Rewards-Farmer#60]
SUGGESTION: Add logging into a `logs` folder in a .log format for troubleshooting and diagnosing issues on headless servers.

**Comment by charlesbel** [comment]
Do you have an idea how to implement that ?

**Comment by koderian** [comment]
Python Logging module

**Comment by JoshuaGarrison27** [comment]
@charlesbel I added logging in my local version of the script. I have not pushed the changes to my repo yet if you want me to add it to my PR for #38

**Comment by joshuamooree** [comment]
I checked in a version that has logging.   Pull request: #248

**Comment by charlesbel** [comment]
Done !
