### ISSUE TITLE
Suggestion: have headless be a command argument when calling the script with python instead of a variable that is changed  in the script

### ISSUE THREAD

**Issue by koderian** [charlesbel/Microsoft-Rewards-Farmer#61]
Make it so headless mode is only valid when --headless argument is added to the runtime command. So when running the script with Python 3 on the terminal, you need to add a additional argument rather then changing the script itself
Example:

headless mode off:
`python3 ms_rewards_farmer.py`

 headless mode on 
`python3 ms_rewards_farmer.py --headless
`

This would be it so headless servers could Git Pull the script (in my case, crontab) without having to edit the script  everytime an update is pulled.

**Comment by charlesbel** [comment]
Fixed with v3.0 #188
