### ISSUE TITLE
Bot will hang on "ENSURING LOGIN ON BING" after the account was unlocked by Microsoft

### ISSUE THREAD

**Issue by Trappy69420** [charlesbel/Microsoft-Rewards-Farmer#62]
So recently on my other account, it was locked by Microsoft which caused it not to be able to log in so I added a phone number and unlocked the account and it still happens. Any trouble shooting ideas?
![Screenshot (171)_LI](https://user-images.githubusercontent.com/81053809/113329292-61295280-92eb-11eb-82a1-0d4dab534395.jpg)

**Comment by charlesbel** [comment]
Your account is probably banned from ms rewards...

**Comment by Trappy69420** [comment]
yeah but i can still login to it and still do the rewards myself tho.

**Comment by Trappy69420** [comment]
plus i can still use bing with that account- so it cannot be banned.

**Comment by charlesbel** [comment]
So it's a country-language problem, make sure you are using an ip adress location matching your microsoft account country-language

**Comment by kaxon-dev** [comment]
I tried running this on an OVH-latest-Ubuntu-VPS and have the same issue. It works locally on Windows 10 but gets stuck on the step described above if using the VPS. The VPS and my home IP share the same country and I'm able to still collect rewards on Windows 10 if I use the VPS as a VPN tunnel via OpenVPN. I don't believe this is an IP or account issue but rather a Linux issue maybe?
