### ISSUE TITLE
Update to use WebDriver of edge

### ISSUE THREAD

**Issue by Lucas559-noob** [charlesbel/Microsoft-Rewards-Farmer#65]
Is possible to update to it use the webdriver of microsoft edge? 
Reason: `*Level 1 members earn up to 5 points a day, 150 points a month, when searching Bing in Microsoft Edge on PC or mobile. Level 2 members earn up to 20 points a day, 600 points a month, when searching Bing in Microsoft Edge on PC or mobile.`

**Comment by charlesbel** [comment]
The script already use the user agents to earn points with edge, there is no need to use the edge webdriver
