### ISSUE TITLE
 Unable to locate element: {"method":"xpath","selector":"//*[@id="rqStartQuiz"]"}

### ISSUE THREAD

**Issue by Wystik-69** [charlesbel/Microsoft-Rewards-Farmer#7]
Hi, 

Thanks for your amazing job, 

Just tested the new version and i get this error (i'm in France, maybe some CSS are exclusive for my country) : 

DevTools listening on ws://127.0.0.1:58431/devtools/browser/1b379069-6a9d-4330-af83-74f39cea1193
Traceback (most recent call last):
  File "C:\Microsoft Rewards\ms_rewards_farmer.py", line 330, in <module>
    completeDailySet(browser)
  File "C:\Microsoft Rewards\ms_rewards_farmer.py", line 211, in completeDailySet
    completeDailySetQuiz(browser, cardNumber)
  File "C:\Microsoft Rewards\ms_rewards_farmer.py", line 152, in completeDailySetQuiz
    browser.find_element_by_xpath('//*[@id="rqStartQuiz"]').click()
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="rqStartQuiz"]"}
  (Session info: chrome=86.0.4240.183)

Thanks,

**Comment by charlesbel** [comment]
L'erreur arrive au démarrage du quiz je suppose, donc est ce que tu pourrait aller manuellement sur le quiz, faire "Inspecter l'élément" sur le bouton "Démarrer le quiz" et me faire une capture d'écran ?

**Comment by Wystik-69** [comment]
Le quiz est déjà lancer, le script à réussi à passer la première question, en essayant toutes les réponses c'est à partir de la deuxième question que ça a planté. 
![image](https://user-images.githubusercontent.com/63404022/98787357-b1b51780-23ff-11eb-9317-125d58549a07.png)

**Comment by charlesbel** [comment]
Enfaite, je sais pourquoi ca plante, le script est incapable de reprendre un quiz en cours de route. Si le quiz est déjà démarré quand le script l'ouvre, il n'arrivera pas à le reprendre là ou il en est. Je te recommanderai de finir ce quiz manuellement, et de réessayer sur celui de demain, en laissant le script faire le quiz du début jusqu'à la fin.

**Comment by Wystik-69** [comment]
Super merci pour ta réponse, je t'avoue que j'ai lancé le script de matin, il a planté en plein milieu du Quiz comme quoi il ne trouvait un "CSS". Du coup forcement il reprenait le script en cours..

**Comment by njhughesSAS** [comment]
This appears to be the same issue as mine this morning i have posted source on my issue.

**Comment by charlesbel** [comment]
I fixed it !

**Comment by Wystik-69** [comment]
L'ensemble à l'air de bien mieux fonctionner, plus d'erreur du tout ! Dernier point si nous n'acceptons pas à la main les coockies (la petite bannières en bas ou par dessus n'importe quelle page) le script n'arrive pas à trouver les boutons des quizs. J'ai fais deux tests ce matin, un sans accepter et un en acceptant. Succès en acceptant dès le début.

L'idée serait que l'instance Chrome soit toujours la même afin que les configurations soient conservées et une fois acceptées plus besoin de réaccepter ou bien que le script sois en mesure de valider la fenêtre d'acceptation des cookies. 

De ce fait, j'avais fait une tâche planifiée Windows au démarrage de ma session en tant que "Système" comme ça plus besoin de me préoccuper du lancement du script et ceci sans avoir une grosse fenêtre qui se lance. Tant que le cookies ne seront pas validé, impossible de lancer le script en headless car il y faut un approbation manuelle. 

----
EN VERSION 

The whole thing seems to work much better, no more errors at all! Last point, if we don't accept by hand the coockies (the little banner at the bottom or on top of any page) the script can't find the quiz buttons. I did two tests this morning, one without accepting and one accepting. Success by accepting from the beginning.

The idea would be that the Chrome instance would always be the same so that the configurations are kept and once accepted no need to reaccept or the script would be able to validate the cookie acceptance window. 

As a result, I had done a Windows scheduled task at the start of my session as a "System" so I didn't have to worry about launching the script and this without having a big window launching. As long as the cookies are not validated, it's impossible to launch the script headless because it requires manual approval.

**Comment by charlesbel** [comment]
J'ai fait une mise à jour, le script accepte les cookies automatiquement, et le mode "headless" fonctionne désormais avec Chrome, et vous pouvez même mettre plusieurs comptes Microsoft, et le script fera l'ensemble des actions sur tous les comptes.
