### ISSUE TITLE
Suggestion: add option for choosing account

### ISSUE THREAD

**Issue by farshadz1997** [charlesbel/Microsoft-Rewards-Farmer#73]
Hello.
some times it stuck on a random stage such as punch cards or Bing searches and make me to restart the program then it checks all accounts which it takes time , it would be nice to add an option at the beginning for choosing which accounts need to be farm and we choose some of them or all.
Thank you

**Comment by charlesbel** [comment]
If the script stuck, it is because you have not the latest version, update it with the latest version
