### ISSUE TITLE
Suggestion: Use explicit waits where using time.sleep() may be wasting time

### ISSUE THREAD

**Issue by Moulik-Budhiraja** [charlesbel/Microsoft-Rewards-Farmer#74]
Explicit wait:
```WebDriverWait(browser, time_to_wait).until(ec.presence_of_element_located((by_, selector)))```

Using explicit waits will speed up the start of searches when waiting for the search bar to appear by only waiting until the given element exists

**Comment by charlesbel** [comment]
I know it, I would suggest you to make a pull request
