### ISSUE TITLE
Selenium Depcriciated.

### ISSUE THREAD

**Issue by Hikaru4v** [charlesbel/Microsoft-Rewards-Farmer#79]
I myself had to fuck around with different selenium versions because everything is depreciated with Selenium 4, causing  some crashes.

maybe add

selenium==3.141.0 
to the requirements file, instead of just having selenium.

**Comment by Hikaru4v** [comment]
Sorry for the bug tag, should have been enhancement.

**Comment by Auftragzkiller** [comment]
I have a fork in which you can use the newest version. I made a pull request too

**Comment by charlesbel** [comment]
Fixed with v3.0 #188
