### ISSUE TITLE
Cannot find cookie accept button

### ISSUE THREAD

**Issue by njhughesSAS** [charlesbel/Microsoft-Rewards-Farmer#8]
I never receive a cookie acceptance button, so I have a crash the new line 75
  File "c:\Users\User\Documents\Microsoft-Rewards-Farmer-master\farmer_test.py", line 75, in login
    browser.find_element_by_id('bnp_btn_accept').click()
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="bnp_btn_accept"]"}

**Comment by njhughesSAS** [comment]
Took keep bot running I put it inside a try except block. 

Could we use web driver to store a cookie in a text file and not have to login every time to avoid this.

**Comment by charlesbel** [comment]
Fixed the error with a try/catch
