### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'ipapi'

### ISSUE THREAD

**Issue by pilonull** [charlesbel/Microsoft-Rewards-Farmer#81]
Trying to run the script. Not sure what's going on here. Running ubuntu.. I've been trying to google this issue and have been having a hard time so I figured I'd ask for help here? 

**Error Log**
> alex@Ubuntu-Plex:~/Desktop/Microsoft-Rewards-Farmer-master$ pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: certifi in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (2019.11.28)
Requirement already satisfied: chardet in /usr/lib/python3/dist-packages (from -r requirements.txt (line 2)) (3.0.4)
Requirement already satisfied: idna in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (2.8)
Requirement already satisfied: requests in /home/alex/.local/lib/python3.9/site-packages (from -r requirements.txt (line 4)) (2.25.1)
Requirement already satisfied: selenium in /home/alex/.local/lib/python3.9/site-packages (from -r requirements.txt (line 5)) (3.141.0)
Requirement already satisfied: urllib3 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 6)) (1.25.8)
Collecting ipapi
  Using cached ipapi-1.0.4-py3-none-any.whl
Installing collected packages: ipapi
Successfully installed ipapi-1.0.4

> alex@Ubuntu-Plex:~/Desktop/Microsoft-Rewards-Farmer-master$ python3 ms_rewards_farmer.py 
Traceback (most recent call last):
  File "ms_rewards_farmer.py", line 7, in <module>
    import ipapi
ModuleNotFoundError: No module named 'ipapi'

**Screenshot of the page**
![image](https://user-images.githubusercontent.com/8344590/160538650-391d9f7f-247a-42e4-a1f0-03464edc59ee.png)

**Source code of dashboard**
not relevant because I don't get that far.

**Comment by charlesbel** [comment]
If you use pip, use python, if you use pip3, use python3. So try to reinstall all requirements with pip3 and run it with python3.

**Comment by pilonull** [comment]
> If you use pip, use python, if you use pip3, use python3. So try to reinstall all requirements with pip3 and run it with python3.

I can't directly remember, but I think my pip/python installation may have been... messed with by me..

![image](https://user-images.githubusercontent.com/8344590/160669463-d114677d-9cd1-4aa8-b5eb-2103db65b2d1.png)

So I'm gonna have to figure that out I guess.

**Comment by pilonull** [comment]
Got it to work on one of my other windows VMs.

Thanks!
