### ISSUE TITLE
Error because I'm stupid and missing something.

### ISSUE THREAD

**Issue by bakapanda1** [charlesbel/Microsoft-Rewards-Farmer#84]
I have an issue where when I start the ms_rewards_farmer.py file it will disappear instantly. 
I followed all the steps and tried from zero again without any success.
I putted all the files in a same folder, I downloaded Python 3.10 also ChromeDriver checking ofc which version of Chrome that I have.
I did on the cmd the pip install -r requirements.txt all fine  and changed the accounts.json.
If there is missing this file (accounts.json) the file ms_rewards_farmer.py doesn't create me any error.
But if there is the file accounts.json, when I try to run the code it will close instantly.
I don't understand the Python language and I asked a friend that use this code and he doesn't have any issue. Any help ?

**Comment by bakapanda1** [comment]
![p1](https://user-images.githubusercontent.com/104598753/166011606-44916433-3c69-4c3e-bae7-68d7cba6c7aa.PNG)
![p2](https://user-images.githubusercontent.com/104598753/166011711-f24d3035-afd3-476e-8af2-ed82fee2028b.PNG)

**Comment by DerMuffin** [comment]
@bakapanda1 Seems like your forgot to place the Chromedriver in C:\Windows Folder or chrome got a update and you need to update the driver too.

"Chromedriver" nexecutable nees to be in PATH

**Comment by bakapanda1** [comment]
@DerMuffin  I fixed this problem by creating a new account on the pc, and doing the process from zero. ( I did the same thing in this main but it didn't work so I don't understand what I'm missing but don't care since from the other account is working :c) 
Ty anyway, have a good day ^^
