### ISSUE TITLE
can i do this on repl.it?

### ISSUE THREAD

**Issue by dystoqia** [charlesbel/Microsoft-Rewards-Farmer#95]
when i try, it doesnt work.
webdriver doesn't work on repl

edit:
this is the error i get.
driver = webdriver.Chrome()

_Originally posted by @nigh95ms in https://github.com/charlesbel/Microsoft-Rewards-Farmer/issues/87#issuecomment-1173149210_

**Comment by Andrew1644563** [comment]
Repl.it will not work, as Chrome WebDriver is a local file, compared to repl.it being online, without access to your hard drive. Just install the latest version of Python, unless well, you can't. In that case, you cannot use the program. Good luck!

**Comment by nigh95ms** [comment]
oh ok thanks for telling me!

**Comment by FRKFFR** [comment]
someone re created the bot https://github.com/MehdiRtal/MicrosoftRewardsBot.git
