### ISSUE TITLE
[BUG] AttributeError: 'WebDriver' object has no attribute 'find_element_by_name'

### ISSUE THREAD

**Issue by Conirefle** [charlesbel/Microsoft-Rewards-Farmer#97]
[LOGIN] Logging-in...
[LOGIN] Writing email...
Traceback (most recent call last):
  File "C:\Users\david\Desktop\Microsoft-Rewards-Farmer-master\ms_rewards_farmer.py", line 773, in <module>
    login(browser, account['username'], account['password'])
  File "C:\Users\david\Desktop\Microsoft-Rewards-Farmer-master\ms_rewards_farmer.py", line 46, in login
    browser.find_element_by_name("loginfmt").send_keys(email)
AttributeError: 'WebDriver' object has no attribute 'find_element_by_name'

Some fix?

**Comment by Power747XD** [comment]
I think this has happened because Selenium has deprecated the function "find_element_by_name". Sadly, I cannot fix this right now, but hopefully someone else will soon.

**Comment by Power747XD** [comment]
As a temporary fix, put this in terminal: `pip install -Iv "selenium===4.2.0"`

This downgrades selenium to a prior version where the error won't appear anymore. However, you will still get a ton of DeprecationWarning warnings. Don't worry, it will work nonetheless.

I will make a pull request to fix this.

**Comment by Power747XD** [comment]
This got fixed in the last commit, pull the latest changes and check if the problem still arises.

**Comment by proximitea** [comment]
After doing that it worked for a few days then stopped working again showing the same error.

**Comment by PrinceJonaa** [comment]
Same here. I still get this error atm. 

[LOGIN] Logging-in...
[LOGIN] Writing email...
Traceback (most recent call last):
  File "C:\Users\jonat\Downloads\Microsoft-Rewards-Farmer-master\Microsoft-Rewards-Farmer-master\ms_rewards_farmer.py", line 773, in <module>
    login(browser, account['username'], account['password'])
  File "C:\Users\jonat\Downloads\Microsoft-Rewards-Farmer-master\Microsoft-Rewards-Farmer-master\ms_rewards_farmer.py", line 46, in login
    browser.find_element_by_name("loginfmt").send_keys(email)
AttributeError: 'WebDriver' object has no attribute 'find_element_by_name'

**Comment by PrinceJonaa** [comment]
> After doing that it worked for a few days then stopped working again showing the same error.

Someone fixed the bug you are having. It's already merged into source; the creator just need to re-release the update. Selenium depreciated the attribute "find_element_by_*"

**Comment by Dangman368** [comment]
just go to requirements.txt and replace selenium with selenium==3.14.1

**Comment by FRKFFR** [comment]
someone re created the bot https://github.com/MehdiRtal/MicrosoftRewardsBot.git

**Comment by charlesbel** [comment]
Fixed with v3.0 #188
